using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Portfolio.Api.Contracts.Common;
using Portfolio.Application.Common.Abstractions.Messaging;
using Portfolio.Application.Features.Phase4B;
using Portfolio.Application.Features.Projects;

namespace Portfolio.Api.Controllers;

[ApiController, Authorize, Route("api/v1/admin/projects")]
public sealed class AdminProjectsController(IRequestDispatcher dispatcher) : ControllerBase
{
    [HttpGet] public async Task<ActionResult<ApiResponse<PagedResult<ProjectListItemResult>>>> List([FromQuery] int page = 1, [FromQuery] int pageSize = 20, [FromQuery] string? search = null, [FromQuery] string? status = null, [FromQuery] bool? featured = null, [FromQuery] bool? isPublished = null, CancellationToken ct = default) => Ok(ApiResponse<PagedResult<ProjectListItemResult>>.Ok(await dispatcher.DispatchAsync(new GetProjectsQuery(page, pageSize, search, status, featured, isPublished), ct)));
    [HttpGet("{id:guid}")] public async Task<ActionResult<ApiResponse<ProjectResult>>> Get(Guid id, CancellationToken ct) => Ok(ApiResponse<ProjectResult>.Ok(await dispatcher.DispatchAsync(new GetProjectQuery(id), ct)));
    [HttpPost] public async Task<ActionResult<ApiResponse<ProjectResult>>> Create(ProjectRequest request, CancellationToken ct) { var result = await dispatcher.DispatchAsync(request.Create(), ct); return CreatedAtAction(nameof(Get), new { id = result.Id }, ApiResponse<ProjectResult>.Ok(result)); }
    [HttpPut("{id:guid}")] public async Task<ActionResult<ApiResponse<ProjectResult>>> Update(Guid id, ProjectRequest request, CancellationToken ct) => Ok(ApiResponse<ProjectResult>.Ok(await dispatcher.DispatchAsync(request.Update(id), ct)));
    [HttpDelete("{id:guid}")] public async Task<IActionResult> Delete(Guid id, CancellationToken ct) { await dispatcher.DispatchAsync(new DeleteProjectCommand(id), ct); return NoContent(); }
    [HttpPut("reorder")] public async Task<ActionResult<ApiResponse>> Reorder(ReorderRequest request, CancellationToken ct) { await dispatcher.DispatchAsync(new ReorderProjectsCommand(request.Items), ct); return Ok(ApiResponse.Ok()); }
    [HttpPut("{projectId:guid}/technologies")] public async Task<ActionResult<ApiResponse<IReadOnlyCollection<ProjectTechnologyResult>>>> ReplaceTechnologies(Guid projectId, ProjectTechnologiesRequest request, CancellationToken ct) => Ok(ApiResponse<IReadOnlyCollection<ProjectTechnologyResult>>.Ok(await dispatcher.DispatchAsync(new ReplaceProjectTechnologiesCommand(projectId, request.Items), ct)));
    [HttpGet("{projectId:guid}/sections")] public async Task<ActionResult<ApiResponse<IReadOnlyCollection<ProjectSectionResult>>>> Sections(Guid projectId, CancellationToken ct) => Ok(ApiResponse<IReadOnlyCollection<ProjectSectionResult>>.Ok(await dispatcher.DispatchAsync(new GetProjectSectionsQuery(projectId), ct)));
    [HttpPost("{projectId:guid}/sections")] public async Task<ActionResult<ApiResponse<ProjectSectionResult>>> CreateSection(Guid projectId, ProjectSectionRequest request, CancellationToken ct) { var result = await dispatcher.DispatchAsync(request.Create(projectId), ct); return StatusCode(StatusCodes.Status201Created, ApiResponse<ProjectSectionResult>.Ok(result)); }
    [HttpPut("{projectId:guid}/sections/{sectionId:guid}")] public async Task<ActionResult<ApiResponse<ProjectSectionResult>>> UpdateSection(Guid projectId, Guid sectionId, ProjectSectionRequest request, CancellationToken ct) => Ok(ApiResponse<ProjectSectionResult>.Ok(await dispatcher.DispatchAsync(request.Update(projectId, sectionId), ct)));
    [HttpDelete("{projectId:guid}/sections/{sectionId:guid}")] public async Task<IActionResult> DeleteSection(Guid projectId, Guid sectionId, CancellationToken ct) { await dispatcher.DispatchAsync(new DeleteProjectSectionCommand(projectId, sectionId), ct); return NoContent(); }
    [HttpPut("{projectId:guid}/sections/reorder")] public async Task<ActionResult<ApiResponse>> ReorderSections(Guid projectId, ReorderRequest request, CancellationToken ct) { await dispatcher.DispatchAsync(new ReorderProjectSectionsCommand(projectId, request.Items), ct); return Ok(ApiResponse.Ok()); }
    [HttpGet("{projectId:guid}/media")] public async Task<ActionResult<ApiResponse<IReadOnlyCollection<ProjectMediaResult>>>> Media(Guid projectId, CancellationToken ct) => Ok(ApiResponse<IReadOnlyCollection<ProjectMediaResult>>.Ok(await dispatcher.DispatchAsync(new GetProjectMediaQuery(projectId), ct)));
    [HttpPost("{projectId:guid}/media")] public async Task<ActionResult<ApiResponse<ProjectMediaResult>>> AttachMedia(Guid projectId, AttachProjectMediaRequest request, CancellationToken ct) { var result = await dispatcher.DispatchAsync(new AttachProjectMediaCommand(projectId, request.MediaAssetId, request.MediaRole, request.Caption, request.DisplayOrder), ct); return StatusCode(StatusCodes.Status201Created, ApiResponse<ProjectMediaResult>.Ok(result)); }
    [HttpPut("{projectId:guid}/media/{projectMediaId:guid}")] public async Task<ActionResult<ApiResponse<ProjectMediaResult>>> UpdateMedia(Guid projectId, Guid projectMediaId, UpdateProjectMediaRequest request, CancellationToken ct) => Ok(ApiResponse<ProjectMediaResult>.Ok(await dispatcher.DispatchAsync(new UpdateProjectMediaCommand(projectId, projectMediaId, request.MediaRole, request.Caption, request.DisplayOrder), ct)));
    [HttpDelete("{projectId:guid}/media/{projectMediaId:guid}")] public async Task<IActionResult> DeleteMedia(Guid projectId, Guid projectMediaId, CancellationToken ct) { await dispatcher.DispatchAsync(new DeleteProjectMediaCommand(projectId, projectMediaId), ct); return NoContent(); }
}
public sealed record ProjectRequest(string Slug, string Title, string? Subtitle, string? ShortDescription, string? OverviewMarkdown, string? Role, int? TeamSize, DateOnly? StartDate, DateOnly? EndDate, string Status, string? GithubUrl, string? LiveUrl, Guid? ThumbnailMediaId, bool Featured, bool IsPublished, int DisplayOrder, string? SeoTitle, string? SeoDescription, IReadOnlyCollection<Guid> TechnologyIds)
{ public CreateProjectCommand Create() => new(Slug, Title, Subtitle, ShortDescription, OverviewMarkdown, Role, TeamSize, StartDate, EndDate, Status, GithubUrl, LiveUrl, ThumbnailMediaId, Featured, IsPublished, DisplayOrder, SeoTitle, SeoDescription, TechnologyIds); public UpdateProjectCommand Update(Guid id) => new(id, Slug, Title, Subtitle, ShortDescription, OverviewMarkdown, Role, TeamSize, StartDate, EndDate, Status, GithubUrl, LiveUrl, ThumbnailMediaId, Featured, IsPublished, DisplayOrder, SeoTitle, SeoDescription, TechnologyIds); }
public sealed record ProjectTechnologiesRequest(IReadOnlyCollection<ProjectTechnologyItem> Items);
public sealed record ProjectSectionRequest(string SectionType, string? Title, string? Subtitle, string? ContentMarkdown, System.Text.Json.JsonElement Content, int DisplayOrder, bool IsVisible)
{ public CreateProjectSectionCommand Create(Guid projectId) => new(projectId, SectionType, Title, Subtitle, ContentMarkdown, Content, DisplayOrder, IsVisible); public UpdateProjectSectionCommand Update(Guid projectId, Guid sectionId) => new(projectId, sectionId, SectionType, Title, Subtitle, ContentMarkdown, Content, DisplayOrder, IsVisible); }
public sealed record AttachProjectMediaRequest(Guid MediaAssetId, string MediaRole, string? Caption, int DisplayOrder);
public sealed record UpdateProjectMediaRequest(string MediaRole, string? Caption, int DisplayOrder);
