import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, convertToParamMap, Router, provideRouter } from '@angular/router';
import { Subject, of, throwError } from 'rxjs';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ApiHttpError } from '../../core/api/api-error.model';
import { DashboardPageComponent } from './dashboard/dashboard-page.component';
import { DashboardService } from './dashboard/dashboard.service';
import { ExperienceEditPageComponent } from './experiences/experience-edit-page.component';
import { ExperienceAdminService } from './experiences/experience-admin.service';
import { ProfileAdminService } from './profile/profile-admin.service';
import { ProfilePageComponent } from './profile/profile-page.component';
import { JourneyAdminService } from './journey/journey-admin.service';
import { JourneyAdminPageComponent } from './journey/journey-page.component';
import { ProjectEditPageComponent } from './projects/project-edit-page.component';
import { ProjectAdminService } from './projects/project-admin.service';
import { SkillAdminService } from './skills/skill-admin.service';
import { SkillsAdminPageComponent } from './skills/skills-page.component';
import { SiteSettingsAdminService } from './site-settings/site-settings-admin.service';
import { SiteSettingsPageComponent } from './site-settings/site-settings-page.component';
import { SocialLinkAdminService } from './social-links/social-link-admin.service';
import { SocialLinksPageComponent } from './social-links/social-links-page.component';
import { TechnologyAdminService } from './technologies/technology-admin.service';

const profile = { id:'p',fullName:'API Admin',professionalTitle:null,secondaryTitle:null,heroHeadline:null,heroSummary:null,aboutMarkdown:null,email:null,phone:null,location:null,university:null,major:null,availabilityStatus:null,profileImage:null,cvMedia:null,isPublished:true,updatedAt:'2026-01-01T00:00:00Z' };
const dashboard = {projects:2,experiences:3,skills:4,certificates:5,knowledge:{indexed:0,pending:0,failed:0},conversations:0,recentUpdates:[]};
const structuredProjectSection = {id:'section-id',sectionType:'ENGINEERING_FOCUS',title:'Key Backend Architecture',subtitle:null,contentMarkdown:null,content:{items:[{title:'Clean Architecture',description:'Separated application, domain, persistence/infrastructure and presentation concerns.'}]},displayOrder:3,isVisible:true};

describe('DashboardPageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  async function render(result:unknown){const api={get:vi.fn(()=>result)};TestBed.overrideComponent(DashboardPageComponent,{set:{providers:[{provide:DashboardService,useValue:api}]}});await TestBed.configureTestingModule({imports:[DashboardPageComponent]}).compileComponents();const fixture=TestBed.createComponent(DashboardPageComponent);fixture.detectChanges();return fixture;}
  it('shows loading while the metric request is pending',async()=>{const fixture=await render(new Subject());expect(fixture.nativeElement.textContent).toContain('Loading dashboard');});
  it('renders only real dashboard metrics and empty updates',async()=>{const fixture=await render(of(dashboard));expect(fixture.nativeElement.textContent).toContain('Projects');expect(fixture.nativeElement.textContent).toContain('No recent updates');expect(fixture.nativeElement.textContent).not.toContain('Visitors');});
  it('shows normalized errors and retry',async()=>{const fixture=await render(throwError(()=>new ApiHttpError(500,{code:'FAILED',message:'Safe dashboard error'})));expect(fixture.nativeElement.textContent).toContain('Safe dashboard error');expect(fixture.nativeElement.textContent).toContain('Retry');});
});

describe('ProfilePageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  function create(update=vi.fn(()=>of(profile))){const api={get:vi.fn(()=>of(profile)),update};TestBed.overrideComponent(ProfilePageComponent,{set:{providers:[{provide:ProfileAdminService,useValue:api}]}});TestBed.configureTestingModule({imports:[ProfilePageComponent]});return {component:TestBed.createComponent(ProfilePageComponent).componentInstance,api};}
  it('loads the singleton profile into the form',()=>{const {component}=create();expect(component.form.controls.fullName.value).toBe('API Admin');expect(component.hasUnsavedChanges()).toBe(false);});
  it('blocks invalid save and tracks dirty state',()=>{const {component,api}=create();component.form.controls.fullName.setValue('');component.form.controls.fullName.markAsDirty();component.save();expect(api.update).not.toHaveBeenCalled();expect(component.hasUnsavedChanges()).toBe(true);});
  it('saves exact typed fields and clears dirty state',()=>{const {component,api}=create();component.form.controls.fullName.setValue('Updated');component.save();expect(api.update).toHaveBeenCalledWith(expect.objectContaining({fullName:'Updated',profileImageId:null,cvMediaId:null}));expect(component.hasUnsavedChanges()).toBe(false);});
  it('surfaces backend validation safely',()=>{const {component}=create(vi.fn(()=>throwError(()=>new ApiHttpError(400,{code:'VALIDATION_ERROR',message:'Review fields',details:{fullName:['Required.']}}))));component.form.controls.fullName.setValue('Valid');component.save();expect(component.error()).toBe('Review fields');});
});

describe('ExperienceEditPageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  function create(){const api={create:vi.fn(()=>of({id:'e1'})),update:vi.fn(),get:vi.fn()};const tech={list:vi.fn(()=>of([{id:'t1',name:'Angular',category:'Frontend',iconKey:null,websiteUrl:null,displayOrder:0,isActive:true,updatedAt:''}]))};const router={navigate:vi.fn()};TestBed.overrideComponent(ExperienceEditPageComponent,{set:{providers:[{provide:ExperienceAdminService,useValue:api}]}});TestBed.configureTestingModule({imports:[ExperienceEditPageComponent],providers:[{provide:TechnologyAdminService,useValue:tech},{provide:Router,useValue:router},{provide:ActivatedRoute,useValue:{snapshot:{paramMap:convertToParamMap({})}}}]});return{component:TestBed.createComponent(ExperienceEditPageComponent).componentInstance,api,router};}
  it('validates required experience fields',()=>{const {component,api}=create();component.save();expect(api.create).not.toHaveBeenCalled();});
  it('creates with unique technology IDs and current-position semantics',()=>{const {component,api}=create();component.form.patchValue({companyName:'Company',roleTitle:'Role',startDate:'2025-01-01',isCurrent:true,endDate:'2025-02-01'});component.toggleTechnology('t1');component.save();expect(api.create).toHaveBeenCalledWith(expect.objectContaining({endDate:null,technologyIds:['t1']}));});
});

describe('ProjectEditPageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  function create(id?:string){const project={id:id??'project-id',slug:'project',title:'Project',subtitle:null,shortDescription:null,overviewMarkdown:null,role:null,teamSize:null,startDate:null,endDate:null,status:'ACTIVE' as const,githubUrl:null,liveUrl:null,thumbnailMediaId:null,thumbnailUrl:null,featured:false,isPublished:true,displayOrder:0,seoTitle:null,seoDescription:null,updatedAt:'',technologies:[{technologyId:'t1',name:'Angular',category:'Frontend',iconKey:null,displayOrder:0}],sections:[structuredProjectSection],media:[]};const projectApi={create:vi.fn(()=>of({id:'new-id'})),get:vi.fn(()=>of(project)),update:vi.fn(),replaceTechnologies:vi.fn(()=>of([])),updateSection:vi.fn(()=>of(structuredProjectSection)),sections:vi.fn(()=>of([])),media:vi.fn(()=>of([]))};const tech={list:vi.fn(()=>of([{id:'t1',name:'Angular',category:'Frontend',iconKey:null,websiteUrl:null,displayOrder:0,isActive:true,updatedAt:''},{id:'t2',name:'TypeScript',category:'Language',iconKey:null,websiteUrl:null,displayOrder:1,isActive:true,updatedAt:''}]))};const router={navigate:vi.fn()};TestBed.overrideComponent(ProjectEditPageComponent,{set:{providers:[{provide:ProjectAdminService,useValue:projectApi}]}});TestBed.configureTestingModule({imports:[ProjectEditPageComponent],providers:[{provide:TechnologyAdminService,useValue:tech},{provide:Router,useValue:router},{provide:ActivatedRoute,useValue:{snapshot:{paramMap:convertToParamMap(id?{id}:{})}}}]});const fixture=TestBed.createComponent(ProjectEditPageComponent);fixture.detectChanges();return{fixture,component:fixture.componentInstance,projectApi,router};}
  it('renders the frozen five-tab editor structure',()=>{const {fixture}=create();const value=fixture.nativeElement.textContent;for(const tab of ['Basic Info','Technologies','Sections','Media','SEO Settings'])expect(value).toContain(tab);});
  it('blocks an invalid project create',()=>{const {component,projectApi}=create();component.saveBasic();expect(projectApi.create).not.toHaveBeenCalled();});
  it('creates a valid project with approved status and technology IDs',()=>{const {component,projectApi,router}=create();component.form.patchValue({title:'Project',slug:'project',status:'ACTIVE'});component.selectedTech.set(['t1']);component.saveBasic();expect(projectApi.create).toHaveBeenCalledWith(expect.objectContaining({status:'ACTIVE',technologyIds:['t1']}));expect(router.navigate).toHaveBeenCalledWith(['/admin/projects','new-id']);});
  it('keeps technology assignment available for an existing project',()=>{const {fixture,component,projectApi}=create('project-id');component.tab.set('Technologies');component.toggleTech('t2');fixture.detectChanges();expect(fixture.nativeElement.querySelectorAll('input[type="checkbox"]')).toHaveLength(2);expect(fixture.nativeElement.textContent).toContain('Save technology assignment');component.replaceTechnologies();expect(projectApi.replaceTechnologies).toHaveBeenCalledWith('project-id',['t1','t2']);});
  it('shows and safely updates structured section content when markdown is empty',()=>{const {fixture,component,projectApi}=create('project-id');component.tab.set('Sections');component.editSection(component.sections()[0]);fixture.detectChanges();const markdown=fixture.nativeElement.querySelector('textarea[formcontrolname="contentMarkdown"]') as HTMLTextAreaElement;const json=fixture.nativeElement.querySelector('textarea[formcontrolname="contentJson"]') as HTMLTextAreaElement;expect(markdown.value).toBe('');expect(json.value).toContain('Clean Architecture');expect(json.value).toContain('Separated application');component.sectionForm.controls.contentJson.setValue(JSON.stringify({items:[{title:'Clean Architecture',description:'Edited safely'}]}));component.saveSection();expect(projectApi.updateSection).toHaveBeenCalledWith('project-id','section-id',expect.objectContaining({contentMarkdown:null,content:{items:[{title:'Clean Architecture',description:'Edited safely'}]}}));});
  it('shows the explicit metadata-only Media placeholder for a new project',()=>{const {fixture,component}=create();component.tab.set('Media');fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Save Basic Info before managing attached media');expect(fixture.nativeElement.textContent).not.toContain('Upload');});
});

describe('SkillsAdminPageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  it('loads the optional Technology selector from the shared catalogue',()=>{const api={list:vi.fn(()=>of([]))};const tech={list:vi.fn(()=>of([{id:'t1',name:'Angular',category:'Frontend',iconKey:null,websiteUrl:null,displayOrder:0,isActive:true,updatedAt:''}]))};TestBed.overrideComponent(SkillsAdminPageComponent,{set:{providers:[{provide:SkillAdminService,useValue:api}]}});TestBed.configureTestingModule({imports:[SkillsAdminPageComponent],providers:[{provide:TechnologyAdminService,useValue:tech}]});const fixture=TestBed.createComponent(SkillsAdminPageComponent);fixture.detectChanges();const selector=fixture.nativeElement.querySelector('select[formcontrolname="technologyId"]') as HTMLSelectElement;expect(tech.list).toHaveBeenCalledOnce();expect([...selector.options].map(option=>option.text.trim())).toEqual(['None','Angular']);});
});

describe('JourneyAdminPageComponent',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  const manual={id:'manual-id',title:'Manual foundation',subtitle:'Custom',description:null,occurredAt:null,iconKey:'code',sourceType:'MANUAL' as const,sourceId:'manual-id',isManual:true,startAt:null,endAt:null,isOngoing:false,timelineKind:'POINT' as const};
  const timeline=[manual,{id:'education-id',title:'BSc',subtitle:'University',description:null,occurredAt:'2020-01-01',iconKey:null,sourceType:'EDUCATION' as const,sourceId:'education-source',isManual:false,startAt:'2020-01-01',endAt:null,isOngoing:true,timelineKind:'PERIOD' as const},{id:'experience-id',title:'Engineer',subtitle:'Company',description:null,occurredAt:'2021-01-01',iconKey:null,sourceType:'EXPERIENCE' as const,sourceId:'experience-source',isManual:false,startAt:'2021-01-01',endAt:'2022-01-01',isOngoing:false,timelineKind:'PERIOD' as const},{id:'project-id',title:'Project',subtitle:'Developer',description:null,occurredAt:'2022-01-01',iconKey:null,sourceType:'PROJECT' as const,sourceId:'project-source',isManual:false,startAt:'2022-01-01',endAt:null,isOngoing:false,timelineKind:'PERIOD' as const},{id:'training-id',title:'Training',subtitle:'Provider',description:null,occurredAt:'2023-01-01',iconKey:null,sourceType:'TRAINING' as const,sourceId:'training-source',isManual:false,startAt:'2023-01-01',endAt:'2023-06-01',isOngoing:false,timelineKind:'PERIOD' as const},{id:'certificate-id',title:'Certificate',subtitle:'Issuer',description:null,occurredAt:'2024-01-01',iconKey:null,sourceType:'CERTIFICATE' as const,sourceId:'certificate-source',isManual:false,startAt:'2024-01-01',endAt:null,isOngoing:false,timelineKind:'POINT' as const}];
  const manualRecord={id:'manual-id',title:'Manual foundation',subtitle:'Custom',description:null,occurredAt:null,iconKey:'code',displayOrder:0,isPublished:true,updatedAt:''};
  function api(){return{timeline:vi.fn(()=>of(timeline)),get:vi.fn(()=>of(manualRecord)),create:vi.fn(()=>of(manualRecord)),update:vi.fn(()=>of(manualRecord)),delete:vi.fn(()=>of(undefined))};}
  it('renders the complete shared timeline in supplied order with source badges',()=>{const service=api();TestBed.overrideComponent(JourneyAdminPageComponent,{set:{providers:[{provide:JourneyAdminService,useValue:service}]}});TestBed.configureTestingModule({imports:[JourneyAdminPageComponent],providers:[provideRouter([])]});const fixture=TestBed.createComponent(JourneyAdminPageComponent);fixture.detectChanges();const items=[...fixture.nativeElement.querySelectorAll('.admin-list-item')] as HTMLElement[];expect(items.map(item=>item.querySelector('strong')?.textContent?.trim())).toEqual(timeline.map(item=>item.title));expect(items.map(item=>item.querySelector('.source-badge')?.textContent?.trim())).toEqual(['Manual','Education','Experience','Project','Training','Certificate']);});
  it('shows generated duration ranges and keeps their dates source-owned',()=>{const service=api();TestBed.overrideComponent(JourneyAdminPageComponent,{set:{providers:[{provide:JourneyAdminService,useValue:service}]}});TestBed.configureTestingModule({imports:[JourneyAdminPageComponent],providers:[provideRouter([])]});const fixture=TestBed.createComponent(JourneyAdminPageComponent);fixture.detectChanges();expect((fixture.nativeElement.querySelector('[data-source-type="EDUCATION"] .timeline-range') as HTMLElement).textContent).toContain('2020-01-01 → Present');expect((fixture.nativeElement.querySelector('[data-source-type="TRAINING"] .timeline-range') as HTMLElement).textContent).toContain('2023-01-01 → 2023-06-01');expect(fixture.nativeElement.textContent).toContain('ordered by their canonical source dates');});
  it('keeps manual CRUD and dirty state but generated rows expose only Edit source',()=>{const service=api();TestBed.overrideComponent(JourneyAdminPageComponent,{set:{providers:[{provide:JourneyAdminService,useValue:service}]}});TestBed.configureTestingModule({imports:[JourneyAdminPageComponent],providers:[provideRouter([])]});const fixture=TestBed.createComponent(JourneyAdminPageComponent);fixture.detectChanges();const manualRow=fixture.nativeElement.querySelector('[data-source-type="MANUAL"]') as HTMLElement;const generated=[...fixture.nativeElement.querySelectorAll('.admin-list-item:not([data-source-type="MANUAL"])')] as HTMLElement[];expect(manualRow.querySelector('[data-action="edit"]')).not.toBeNull();expect(manualRow.querySelector('[data-action="delete"]')).not.toBeNull();expect(manualRow.querySelector('[data-action="edit-source"]')).toBeNull();for(const row of generated){expect(row.querySelector('[data-action="edit"]')).toBeNull();expect(row.querySelector('[data-action="delete"]')).toBeNull();expect(row.querySelector('[data-action="edit-source"]')).not.toBeNull();}expect(fixture.componentInstance.sourceRoute(timeline[1])).toEqual(['/admin/education']);expect(fixture.componentInstance.sourceRoute(timeline[2])).toEqual(['/admin/experience','experience-source']);expect(fixture.componentInstance.sourceRoute(timeline[3])).toEqual(['/admin/projects','project-source']);expect(fixture.componentInstance.sourceRoute(timeline[4])).toEqual(['/admin/trainings']);expect(fixture.componentInstance.sourceRoute(timeline[5])).toEqual(['/admin/certificates']);fixture.componentInstance.edit(manual);expect(service.get).toHaveBeenCalledWith('manual-id');fixture.componentInstance.form.controls.title.setValue('Changed');fixture.componentInstance.form.controls.title.markAsDirty();expect(fixture.componentInstance.hasUnsavedChanges()).toBe(true);fixture.componentInstance.edit(null);expect(fixture.componentInstance.hasUnsavedChanges()).toBe(false);});
  it('creates only a manual milestone through the existing CRUD service',()=>{const service=api();TestBed.overrideComponent(JourneyAdminPageComponent,{set:{providers:[{provide:JourneyAdminService,useValue:service}]}});TestBed.configureTestingModule({imports:[JourneyAdminPageComponent],providers:[provideRouter([])]});const fixture=TestBed.createComponent(JourneyAdminPageComponent);fixture.detectChanges();fixture.componentInstance.form.controls.title.setValue('Custom milestone');fixture.componentInstance.save();expect(service.create).toHaveBeenCalledWith(expect.objectContaining({title:'Custom milestone'}));expect(service.update).not.toHaveBeenCalled();});
});

describe('typed settings and social URL safety',()=>{
  beforeEach(()=>TestBed.resetTestingModule());
  it('loads and saves only typed site settings while tracking dirtiness',()=>{const settings={siteName:'Site',footerText:null,showAvailability:true,showDownloadCv:false,showJourney:true,showAiAgent:false,defaultSeoTitle:null,defaultSeoDescription:null};const api={get:vi.fn(()=>of(settings)),update:vi.fn((_value:unknown)=>of(settings))};TestBed.overrideComponent(SiteSettingsPageComponent,{set:{providers:[{provide:SiteSettingsAdminService,useValue:api}]}});TestBed.configureTestingModule({imports:[SiteSettingsPageComponent]});const component=TestBed.createComponent(SiteSettingsPageComponent).componentInstance;component.form.controls.siteName.setValue('Updated');component.save();expect(api.update).toHaveBeenCalledWith(expect.objectContaining({siteName:'Updated'}));expect(Object.keys(api.update.mock.calls[0][0] as object)).toHaveLength(8);expect(component.hasUnsavedChanges()).toBe(false);});
  it('rejects unsafe social URLs before API submission',()=>{const api={list:vi.fn(()=>of([])),create:vi.fn(),update:vi.fn()};TestBed.overrideComponent(SocialLinksPageComponent,{set:{providers:[{provide:SocialLinkAdminService,useValue:api}]}});TestBed.configureTestingModule({imports:[SocialLinksPageComponent]});const component=TestBed.createComponent(SocialLinksPageComponent).componentInstance;component.form.patchValue({platform:'Bad',url:'javascript:alert(1)'});component.save();expect(api.create).not.toHaveBeenCalled();});
});
