import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, take } from 'rxjs';
import { safeAdminError } from '../admin/shared/admin-api';
import { AgentService } from './agent.service';
import { ChatSource } from './agent.models';
interface Line { role:'USER'|'ASSISTANT'; content:string; id?:string; sources?:ChatSource[] }
@Component({selector:'app-chat-widget',imports:[FormsModule],template:`<button class="launcher" type="button" (click)="toggle()" [attr.aria-expanded]="open()" aria-controls="portfolio-chat">{{open()?'Close':'Ask AI'}}</button>@if(open()){<section id="portfolio-chat" class="chat" aria-label="Portfolio assistant"><header><strong>Portfolio assistant</strong><button type="button" (click)="open.set(false)" aria-label="Close chat">×</button></header><div class="messages" aria-live="polite">@for(x of lines();track $index){<article [class.user]="x.role==='USER'"><p>{{x.content}}</p>@if(x.sources?.length){<ul>@for(s of x.sources;track s.rank){<li>@if(s.projectSlug){<a [href]="'/projects/'+s.projectSlug">{{s.title}}</a>}@else{<span>{{s.title}}</span>} · {{s.similarityScore}}</li>}</ul>}@if(x.role==='ASSISTANT'&&x.id){<div><button type="button" (click)="rate(x.id,'POSITIVE')">Helpful</button><button type="button" (click)="rate(x.id,'NEGATIVE')">Not helpful</button></div>}</article>}@if(loading()){<p>Thinking…</p>}@if(error()){<p class="error" role="alert">{{error()}}</p>}</div><form (ngSubmit)="send()"><label class="sr-only" for="chat-message">Message</label><textarea id="chat-message" [(ngModel)]="draft" name="message" maxlength="2000" rows="2" placeholder="Ask about experience, projects, or skills"></textarea><button type="submit" [disabled]="loading()||!draft.trim()">Send</button></form></section>}`,styles:`.launcher{position:fixed;right:1.25rem;bottom:1.25rem;z-index:60;border:0;border-radius:999px;padding:.9rem 1.1rem;background:var(--color-primary);color:#07111f;font-weight:800}.chat{position:fixed;right:1.25rem;bottom:5rem;z-index:60;width:min(24rem,calc(100vw - 2rem));max-height:min(40rem,75vh);display:grid;grid-template-rows:auto 1fr auto;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface);box-shadow:0 1.5rem 4rem #0008;overflow:hidden}.chat header,.chat form{display:flex;gap:.75rem;padding:.85rem;border-bottom:1px solid var(--color-border)}.chat header{justify-content:space-between}.messages{padding:.85rem;overflow:auto}.messages article{margin:.6rem 0;padding:.7rem;border-radius:.75rem;background:var(--color-surface-high)}.messages article.user{margin-left:2rem;background:color-mix(in srgb,var(--color-primary) 18%,var(--color-surface))}p{white-space:pre-wrap;margin:0}ul{padding-left:1rem;font-size:.8rem}textarea{flex:1;resize:none}.error{color:var(--color-error)}button{cursor:pointer}`})
export class ChatWidgetComponent { private api=inject(AgentService);readonly open=signal(false);readonly loading=signal(false);readonly error=signal<string|null>(null);readonly lines=signal<Line[]>([]);session:string|null=null;draft='';toggle(){this.open.update(x=>!x);if(this.open()&&!this.session)this.start()}start(){this.loading.set(true);this.api.createSession().pipe(take(1),finalize(()=>this.loading.set(false))).subscribe({next:x=>{this.session=x.sessionId;if(x.welcomeMessage)this.lines.set([{role:'ASSISTANT',content:x.welcomeMessage}])},error:e=>this.error.set(safeAdminError(e))})}send(){const message=this.draft.trim();if(!message||!this.session)return;this.lines.update(x=>[...x,{role:'USER',content:message}]);this.draft='';this.loading.set(true);this.error.set(null);this.api.send(this.session,message).pipe(take(1),finalize(()=>this.loading.set(false))).subscribe({next:x=>this.lines.update(v=>[...v,{role:'ASSISTANT',content:x.answer,id:x.messageId,sources:x.sources}]),error:e=>this.error.set(safeAdminError(e))})}rate(id:string,rating:'POSITIVE'|'NEGATIVE'){this.api.feedback(id,rating).pipe(take(1)).subscribe({error:e=>this.error.set(safeAdminError(e))})}}
