using Microsoft.EntityFrameworkCore;
using Portfolio.Application.Common.Abstractions.Storage;
using Portfolio.Application.Common.Abstractions.Persistence;
using Portfolio.Application.Common.Exceptions;
using Portfolio.Application.Features.Media;
using Portfolio.Domain.Entities;
using Portfolio.UnitTests.Authentication;
using Microsoft.Extensions.Options;
using Portfolio.Infrastructure.Storage;

namespace Portfolio.UnitTests.PortfolioContent;

public sealed class MediaFeatureTests
{
    private static readonly DateTimeOffset Now = new(2026, 8, 28, 10, 0, 0, TimeSpan.Zero);

    [Fact] public async Task Upload_validates_signature_stores_file_and_persists_safe_metadata()
    { await using var db=PublicPortfolioTests.CreateContext();var storage=new FakeStorage();await using var stream=new MemoryStream([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0,0,0,0]);var result=await new UploadMediaCommandHandler(db,storage,new FixedTimeProvider(Now)).HandleAsync(new(stream,"../avatar.png","image/png",stream.Length,"image"," Avatar "));Assert.Equal("IMAGE",result.MediaType);Assert.Equal("avatar.png",result.FileName);Assert.Equal("Avatar",result.AltText);Assert.StartsWith("portfolio/2026/08/",result.StorageKey);Assert.Equal(result.StorageKey,storage.UploadedKey);Assert.Single(await db.MediaAssets.ToListAsync()); }

    [Fact] public async Task Upload_rejects_spoofed_unsupported_oversized_and_incompatible_files()
    { await using var db=PublicPortfolioTests.CreateContext();var handler=new UploadMediaCommandHandler(db,new FakeStorage(),new FixedTimeProvider(Now));await Assert.ThrowsAsync<ValidationException>(()=>handler.HandleAsync(new(new MemoryStream("<script>"u8.ToArray()),"x.png","image/png",8,"IMAGE",null)));await Assert.ThrowsAsync<ValidationException>(()=>handler.HandleAsync(new(new MemoryStream("%PDF-"u8.ToArray()),"x.svg","image/svg+xml",5,"IMAGE",null)));await Assert.ThrowsAsync<ValidationException>(()=>handler.HandleAsync(new(new MemoryStream("%PDF-"u8.ToArray()),"x.pdf","application/pdf",10*1024*1024+1,"DOCUMENT",null)));await Assert.ThrowsAsync<ValidationException>(()=>handler.HandleAsync(new(new MemoryStream("%PDF-"u8.ToArray()),"x.pdf","application/pdf",5,"IMAGE",null)));Assert.Empty(await db.MediaAssets.ToListAsync()); }

    [Fact] public async Task Upload_storage_failure_creates_no_row_and_database_failure_attempts_cleanup()
    { await using var db=PublicPortfolioTests.CreateContext();var failedStorage=new FakeStorage{FailUpload=true};await Assert.ThrowsAsync<IOException>(()=>new UploadMediaCommandHandler(db,failedStorage,new FixedTimeProvider(Now)).HandleAsync(Png()));Assert.Empty(await db.MediaAssets.ToListAsync());var cleanupStorage=new FakeStorage();await Assert.ThrowsAsync<DbUpdateException>(()=>new UploadMediaCommandHandler(new SaveFailingContext(db),cleanupStorage,new FixedTimeProvider(Now)).HandleAsync(Png()));Assert.NotNull(cleanupStorage.DeletedKey); }

    [Fact] public async Task List_filters_searches_pages_and_orders_deterministically()
    { await using var db=PublicPortfolioTests.CreateContext();var a=Asset("a.png","IMAGE",Now,Guid.Parse("00000000-0000-0000-0000-000000000001"));var b=Asset("school.pdf","DOCUMENT",Now,Guid.Parse("00000000-0000-0000-0000-000000000002"));var c=Asset("school.png","IMAGE",Now.AddMinutes(1),Guid.NewGuid());db.MediaAssets.AddRange(a,b,c);await db.SaveChangesAsync();var all=await new GetMediaQueryHandler(db).HandleAsync(new(1,20));var filtered=await new GetMediaQueryHandler(db).HandleAsync(new(1,20,"IMAGE","school"));Assert.Equal(new[]{c.Id,b.Id,a.Id},all.Items.Select(x=>x.Id));Assert.Equal(c.Id,filtered.Items.Single().Id);Assert.Equal(3,all.Total); }

    [Fact] public async Task Update_is_metadata_only_and_enforces_type_compatibility_and_not_found()
    { await using var db=PublicPortfolioTests.CreateContext();var x=Asset("cv.pdf","DOCUMENT",Now,Guid.NewGuid());x.MimeType="application/pdf";db.MediaAssets.Add(x);await db.SaveChangesAsync();var updated=await new UpdateMediaCommandHandler(db,new FixedTimeProvider(Now.AddDays(1))).HandleAsync(new(x.Id," CV ","CV"));Assert.Equal("CV",updated.MediaType);Assert.Equal("CV",updated.AltText);Assert.Equal(x.StorageKey,updated.StorageKey);await Assert.ThrowsAsync<ValidationException>(()=>new UpdateMediaCommandHandler(db,new FixedTimeProvider(Now)).HandleAsync(new(x.Id,null,"IMAGE")));await Assert.ThrowsAsync<NotFoundException>(()=>new UpdateMediaCommandHandler(db,new FixedTimeProvider(Now)).HandleAsync(new(Guid.NewGuid(),null,"CV"))); }

    [Fact] public async Task Delete_rejects_references_and_keeps_metadata_when_storage_fails()
    { await using var db=PublicPortfolioTests.CreateContext();var used=Asset("used.png","IMAGE",Now,Guid.NewGuid());var free=Asset("free.png","IMAGE",Now,Guid.NewGuid());db.MediaAssets.AddRange(used,free);db.Projects.Add(new Project{Id=Guid.NewGuid(),Slug="p",Title="p",Status="ACTIVE",ThumbnailMediaId=used.Id});await db.SaveChangesAsync();var conflict=await Assert.ThrowsAsync<ConflictException>(()=>new DeleteMediaCommandHandler(db,new FakeStorage()).HandleAsync(new(used.Id)));Assert.Equal("MEDIA_IN_USE",conflict.Code);var failing=new FakeStorage{FailDelete=true};await Assert.ThrowsAsync<IOException>(()=>new DeleteMediaCommandHandler(db,failing).HandleAsync(new(free.Id)));Assert.True(await db.MediaAssets.AnyAsync(x=>x.Id==free.Id));var ok=new FakeStorage();await new DeleteMediaCommandHandler(db,ok).HandleAsync(new(free.Id));Assert.Equal(free.StorageKey,ok.DeletedKey);Assert.False(await db.MediaAssets.AnyAsync(x=>x.Id==free.Id)); }

    [Fact] public async Task R2_storage_fails_clearly_on_use_when_configuration_is_missing()
    { var storage=new R2FileStorage(Options.Create(new R2Settings()));var error=await Assert.ThrowsAsync<InvalidOperationException>(()=>storage.DeleteAsync("portfolio/key"));Assert.Contains("R2 storage is not configured",error.Message); }

    private static MediaAsset Asset(string name,string type,DateTimeOffset at,Guid id)=>new(){Id=id,StorageKey=$"portfolio/{name}",PublicUrl=$"https://cdn.example/{name}",FileName=name,MimeType=type=="IMAGE"?"image/png":"application/pdf",FileSize=10,MediaType=type,CreatedAt=at,UpdatedAt=at};
    private static UploadMediaCommand Png(){var s=new MemoryStream([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);return new(s,"a.png","image/png",s.Length,"IMAGE",null);}
    private sealed class FakeStorage:IFileStorage { public string? UploadedKey{get;private set;}public string? DeletedKey{get;private set;}public bool FailDelete{get;init;}public bool FailUpload{get;init;}public Task<string> UploadAsync(string key,Stream content,string contentType,CancellationToken ct=default){if(FailUpload)throw new IOException("R2 unavailable");UploadedKey=key;return Task.FromResult($"https://cdn.example/{key}");}public Task DeleteAsync(string key,CancellationToken ct=default){if(FailDelete)throw new IOException("R2 unavailable");DeletedKey=key;return Task.CompletedTask;} }
    private sealed class SaveFailingContext(ContentTestDbContext inner):IApplicationDbContext { public DbSet<AdminUser> AdminUsers=>throw new NotSupportedException();public DbSet<AdminRefreshToken> AdminRefreshTokens=>throw new NotSupportedException();public DbSet<MediaAsset> MediaAssets=>inner.MediaAssets;public DbSet<Profile> Profiles=>inner.Profiles;public DbSet<Experience> Experiences=>inner.Experiences;public DbSet<Technology> Technologies=>inner.Technologies;public DbSet<ExperienceTechnology> ExperienceTechnologies=>inner.ExperienceTechnologies;public DbSet<Project> Projects=>inner.Projects;public DbSet<ProjectTechnology> ProjectTechnologies=>inner.ProjectTechnologies;public DbSet<ProjectSection> ProjectSections=>inner.ProjectSections;public DbSet<ProjectMedia> ProjectMedia=>inner.ProjectMedia;public DbSet<Skill> Skills=>inner.Skills;public DbSet<Education> Educations=>inner.Educations;public DbSet<Training> Trainings=>inner.Trainings;public DbSet<Certificate> Certificates=>inner.Certificates;public DbSet<JourneyItem> JourneyItems=>inner.JourneyItems;public DbSet<SocialLink> SocialLinks=>inner.SocialLinks;public DbSet<SiteSetting> SiteSettings=>inner.SiteSettings;public DbSet<ContactMessage> ContactMessages=>inner.ContactMessages;public DbSet<AgentSetting> AgentSettings=>throw new NotSupportedException();public DbSet<KnowledgeDocument> KnowledgeDocuments=>inner.KnowledgeDocuments;public DbSet<KnowledgeChunk> KnowledgeChunks=>throw new NotSupportedException();public DbSet<ChatSession> ChatSessions=>inner.ChatSessions;public DbSet<ChatMessage> ChatMessages=>throw new NotSupportedException();public DbSet<ChatMessageSource> ChatMessageSources=>throw new NotSupportedException();public DbSet<ChatMessageFeedback> ChatMessageFeedback=>throw new NotSupportedException();public Task<int> SaveChangesAsync(CancellationToken ct=default)=>throw new DbUpdateException("Simulated failure"); }
}
