import { Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { take } from 'rxjs';
import { isSafeAdminUrl, nullable, safeAdminError } from '../shared/admin-api';
import { Technology, TechnologyRequest } from '../shared/admin.models';
import { DirtyAware } from '../shared/dirty.guard';
import { TechnologyAdminService } from './technology-admin.service';

@Component({
  selector: 'app-technology-manager',
  imports: [ReactiveFormsModule],
  template: `<section class="admin-panel technology-manager"><header><div><p class="eyebrow">Project catalogue</p><h2>Technologies</h2><p>Manage the technologies available to project and skill editors.</p></div><button class="admin-button" type="button" (click)="edit(null)">New technology</button></header><div class="technology-layout"><ul class="admin-list">@for(item of items();track item.id){<li class="admin-list-item"><div><strong>{{item.name}}</strong><p>{{item.category}} · {{item.isActive?'Active':'Inactive'}}</p></div><div class="admin-actions"><button class="admin-button" type="button" (click)="edit(item)">Edit</button>@if(confirming()===item.id){<button class="admin-button danger" type="button" (click)="remove(item.id)">Confirm delete</button><button class="admin-button" type="button" (click)="confirming.set(null)">Cancel</button>}@else{<button class="admin-button danger" type="button" (click)="confirming.set(item.id)">Delete</button>}</div></li>}</ul><form class="admin-form" [formGroup]="form" (ngSubmit)="save()"><h3>{{editingId()?'Edit':'Add'}} technology</h3><label>Name<input formControlName="name" maxlength="255"/></label><label>Category<input formControlName="category" maxlength="100"/></label><label>Icon key<input formControlName="iconKey" maxlength="100"/></label><label>Website URL<input type="url" formControlName="websiteUrl"/>@if(form.controls.websiteUrl.dirty&&!safeUrl(form.controls.websiteUrl.value)){<span class="field-error">Use an HTTP or HTTPS URL.</span>}</label><label>Display order<input type="number" min="0" formControlName="displayOrder"/></label><label><span><input type="checkbox" formControlName="isActive"/> Active</span></label>@if(error()){<p class="admin-error" role="alert">{{error()}}</p>}<div class="admin-actions"><button class="admin-button primary" type="submit">Save technology</button><button class="admin-button" type="button" (click)="edit(null)">Clear</button></div></form></div></section>`,
  styles: `.technology-manager{margin-top:1.5rem}.technology-manager>header{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1.5rem}.technology-manager h2,.technology-manager h3{margin:.25rem 0}.technology-manager header p:last-child,.admin-list p{margin:.25rem 0;color:var(--color-text-muted)}.technology-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(18rem,.65fr);gap:1.5rem}@media(max-width:850px){.technology-layout{grid-template-columns:1fr}.technology-manager>header{flex-direction:column}}`,
  providers: [TechnologyAdminService],
})
export class TechnologyManagerComponent implements DirtyAware {
  private api=inject(TechnologyAdminService); readonly safeUrl=(value:string)=>!value||isSafeAdminUrl(value)&&!value.startsWith('mailto:'); readonly items=signal<Technology[]>([]); readonly editingId=signal<string|null>(null); readonly confirming=signal<string|null>(null); readonly error=signal<string|null>(null);
  readonly form=new FormGroup({name:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(255)]}),category:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(100)]}),iconKey:new FormControl('',{nonNullable:true,validators:[Validators.maxLength(100)]}),websiteUrl:new FormControl('',{nonNullable:true}),displayOrder:new FormControl(0,{nonNullable:true,validators:[Validators.min(0)]}),isActive:new FormControl(true,{nonNullable:true})});
  constructor(){this.load()} load(){this.api.list().pipe(take(1)).subscribe({next:x=>this.items.set(x),error:e=>this.error.set(safeAdminError(e))})}
  edit(item:Technology|null){this.editingId.set(item?.id??null);this.form.reset(item?{...item,iconKey:item.iconKey??'',websiteUrl:item.websiteUrl??''}:{name:'',category:'',iconKey:'',websiteUrl:'',displayOrder:this.items().length,isActive:true})}
  save(){if(this.form.invalid||!this.safeUrl(this.form.controls.websiteUrl.value)){this.form.markAllAsTouched();return}const v=this.form.getRawValue();const body:TechnologyRequest={...v,iconKey:nullable(v.iconKey),websiteUrl:nullable(v.websiteUrl)};const id=this.editingId();(id?this.api.update(id,body):this.api.create(body)).pipe(take(1)).subscribe({next:()=>{this.edit(null);this.load()},error:e=>this.error.set(safeAdminError(e))})}
  remove(id:string){this.api.delete(id).pipe(take(1)).subscribe({next:()=>{this.confirming.set(null);this.edit(null);this.load()},error:e=>this.error.set(safeAdminError(e))})} hasUnsavedChanges(){return this.form.dirty}
}
