import { Component, inject } from '@angular/core';
import { EmptyStateComponent } from '../../../shared/components/empty-state/empty-state.component';
import { LoadingIndicatorComponent } from '../../../shared/components/loading-indicator/loading-indicator.component';
import { PortfolioStore } from '../shared/portfolio.store';
import { formatPortfolioDate, safeHttpUrl } from '../shared/public-utils';

@Component({ selector: 'app-experience-page', imports: [EmptyStateComponent, LoadingIndicatorComponent], template: `
  <div class="public-page"><header class="page-heading"><span class="eyebrow">Professional path</span><h1>Experience</h1></header>
  @if (store.status() === 'loading' || store.status() === 'idle') { <div class="state-panel"><app-loading-indicator label="Loading experience" /></div> }
  @else if (store.status() === 'error') { <div class="state-panel" role="alert"><p>{{ store.error() }}</p><button class="retry-button" type="button" (click)="store.retry()">Try again</button></div> }
  @else if (store.data(); as data) {
    @if (data.experiences.length) { <section class="section-block"><h2>Work</h2><div class="timeline">@for (item of data.experiences; track item.id) { <article><div class="period">{{ date(item.startDate) }} @if (item.isCurrent) { &ndash; Present } @else if (date(item.endDate); as end) { &ndash; {{ end }} }</div><h3>{{ item.roleTitle }}</h3><p class="organization">{{ item.companyName }}@if (item.location) { &middot; {{ item.location }} }</p>@if (item.summary) { <p>{{ item.summary }}</p> }@if (item.responsibilitiesMarkdown) { <p class="pre-line">{{ item.responsibilitiesMarkdown }}</p> }@if (item.technologies.length) { <ul class="chip-list">@for (technology of item.technologies; track technology.id) { <li>{{ technology.name }}</li> }</ul> }@if (http(item.companyUrl); as url) { <a class="text-link" [href]="url" target="_blank" rel="noopener noreferrer">Company website</a> }</article> }</div></section> }
    @if (data.educations.length) { <section class="section-block"><h2>Education</h2><div class="detail-grid">@for (item of data.educations; track item.id) { <article><h3>{{ item.institution }}</h3>@if (item.degree || item.fieldOfStudy) { <p>{{ item.degree }} @if (item.degree && item.fieldOfStudy) { &middot; } {{ item.fieldOfStudy }}</p> }@if (item.description) { <p>{{ item.description }}</p> }<span>{{ date(item.startDate) }} @if (date(item.endDate); as end) { &ndash; {{ end }} }</span></article> }</div></section> }
    @if (data.trainings.length) { <section class="section-block"><h2>Training</h2><div class="detail-grid">@for (item of data.trainings; track item.id) { <article><h3>{{ item.title }}</h3>@if (item.provider) { <p>{{ item.provider }}</p> }@if (item.description) { <p>{{ item.description }}</p> }@if (http(item.credentialUrl); as url) { <a class="text-link" [href]="url" target="_blank" rel="noopener noreferrer">View credential</a> }</article> }</div></section> }
    @if (data.certificates.length) { <section class="section-block"><h2>Certificates</h2><div class="detail-grid">@for (item of data.certificates; track item.id) { <article><h3>{{ item.name }}</h3>@if (item.issuer) { <p>{{ item.issuer }}</p> }@if (date(item.issuedAt); as issued) { <span>Issued {{ issued }}</span> }@if (http(item.credentialUrl || item.certificateUrl); as url) { <a class="text-link" [href]="url" target="_blank" rel="noopener noreferrer">View certificate</a> }</article> }</div></section> }
    @if (!data.experiences.length && !data.educations.length && !data.trainings.length && !data.certificates.length) { <app-empty-state title="No experience published" message="Experience and learning history will appear here." /> }
  }
  </div>`, styles: `.timeline { border-left: 1px solid var(--color-border); margin-left: .4rem; } .timeline article { position: relative; max-width: 54rem; padding: 0 0 3rem 2rem; } .timeline article::before { content: ''; position: absolute; left: -.38rem; top: .35rem; width: .7rem; height: .7rem; border-radius: 50%; background: var(--color-primary); } .period, article span { color: var(--color-primary); font-size: .8rem; } article p { color: var(--color-text-muted); } .organization { color: var(--color-text) !important; } .detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 18rem), 1fr)); gap: 1rem; } .detail-grid article { padding: 1.25rem; border: 1px solid var(--color-border); border-radius: var(--radius-lg); } .detail-grid .text-link { display: block; margin-top: 1rem; }` })
export class ExperiencePageComponent { readonly store = inject(PortfolioStore); readonly date = formatPortfolioDate; readonly http = safeHttpUrl; constructor() { this.store.load(); } }
