using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using Microsoft.Extensions.DependencyInjection;using Portfolio.Application.Common.Abstractions.Authentication;using Portfolio.IntegrationTests.Authentication;
namespace Portfolio.IntegrationTests.PortfolioContent;
public sealed class AgentApiTests(AuthApiFactory factory):IClassFixture<AuthApiFactory>
{
 [Theory][InlineData("/api/v1/admin/agent/settings")][InlineData("/api/v1/admin/agent/knowledge")][InlineData("/api/v1/admin/agent/conversations")]public async Task Admin_agent_routes_require_authentication(string url)=>Assert.Equal(HttpStatusCode.Unauthorized,(await factory.CreateClient().GetAsync(url)).StatusCode);
 [Fact]public async Task Public_chat_session_message_and_feedback_match_contract(){var client=factory.CreateClient();var created=await client.PostAsJsonAsync("/api/v1/public/chat/sessions",new{});Assert.Equal(HttpStatusCode.Created,created.StatusCode);var message=await client.PostAsJsonAsync("/api/v1/public/chat/sessions/77777777-7777-7777-7777-777777777777/messages",new{message="Project?"});Assert.Equal(HttpStatusCode.OK,message.StatusCode);var json=await message.Content.ReadAsStringAsync();Assert.Contains("Grounded answer",json);Assert.Contains("sources",json);var feedback=await client.PostAsJsonAsync("/api/v1/public/chat/messages/66666666-6666-6666-6666-666666666666/feedback",new{rating="POSITIVE"});Assert.Equal(HttpStatusCode.Created,feedback.StatusCode);}
 [Fact]public async Task Public_chat_validates_input_and_invalid_session(){var client=factory.CreateClient();var invalid=await client.PostAsJsonAsync("/api/v1/public/chat/sessions/77777777-7777-7777-7777-777777777777/messages",new{message=""});Assert.Equal(HttpStatusCode.BadRequest,invalid.StatusCode);var missing=await client.PostAsJsonAsync("/api/v1/public/chat/sessions/11111111-1111-1111-1111-111111111111/messages",new{message="Hi"});Assert.Equal(HttpStatusCode.NotFound,missing.StatusCode);}
 [Fact]public async Task Public_chat_maps_provider_failures_to_sanitized_service_unavailable(){var response=await factory.CreateClient().PostAsJsonAsync("/api/v1/public/chat/sessions/77777777-7777-7777-7777-777777777777/messages",new{message="provider-error"});Assert.Equal(HttpStatusCode.ServiceUnavailable,response.StatusCode);var body=await response.Content.ReadAsStringAsync();Assert.Contains("AGENT_UNAVAILABLE",body);Assert.DoesNotContain("credential",body,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Authenticated_admin_can_manage_agent_knowledge_and_conversations(){var client=Authenticated();Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/v1/admin/agent/settings")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.PutAsJsonAsync("/api/v1/admin/agent/settings",new{enabled=true,provider="OpenAI",modelName="chat",embeddingProvider="OpenAI",embeddingModel="embed",systemPrompt="Ground",welcomeMessage="Hi",fallbackMessage="No",maxContextChunks=6,minimumSimilarity=.6,temperature=.2})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/v1/admin/agent/knowledge")).StatusCode);Assert.Equal(HttpStatusCode.Accepted,(await client.PostAsJsonAsync("/api/v1/admin/agent/knowledge/reindex-all",new{})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/v1/admin/agent/conversations")).StatusCode);}
 private HttpClient Authenticated(){var c=factory.CreateClient();using var s=factory.Services.CreateScope();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",s.ServiceProvider.GetRequiredService<IJwtTokenService>().CreateAccessToken(AuthApiFactory.AdminId,"admin@example.com").Value);return c;}
}
