using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Portfolio.Application.Common.Abstractions.AI;
using Portfolio.Application.Common.Abstractions.Messaging;
using Portfolio.Application.Common.Abstractions.Persistence;
using Portfolio.Application.Common.Abstractions.Validation;
using Portfolio.Application.Common.Exceptions;
using Portfolio.Application.Common.Models;
using Portfolio.Domain.Entities;

namespace Portfolio.Application.Features.Agent;

public sealed record AgentSettingsResult(Guid Id,string Name,bool Enabled,string? Provider,string? ModelName,string? EmbeddingProvider,string? EmbeddingModel,int EmbeddingDimensions,string SystemPrompt,string? WelcomeMessage,string? FallbackMessage,int MaxContextChunks,decimal? MinimumSimilarity,decimal Temperature);
public sealed record GetAgentSettingsQuery:IRequest<AgentSettingsResult>;
public sealed record UpdateAgentSettingsCommand(bool Enabled,string? Provider,string? ModelName,string? EmbeddingProvider,string? EmbeddingModel,string SystemPrompt,string? WelcomeMessage,string? FallbackMessage,int MaxContextChunks,decimal? MinimumSimilarity,decimal Temperature):IRequest<AgentSettingsResult>;
public sealed class GetAgentSettingsQueryHandler(IApplicationDbContext db):IRequestHandler<GetAgentSettingsQuery,AgentSettingsResult>{public async Task<AgentSettingsResult> HandleAsync(GetAgentSettingsQuery r,CancellationToken ct=default)=>Map(await db.AgentSettings.AsNoTracking().SingleOrDefaultAsync(x=>x.Name=="portfolio-agent",ct)??throw new NotFoundException("AGENT_SETTINGS_NOT_FOUND","Agent settings were not found."));internal static AgentSettingsResult Map(AgentSetting x)=>new(x.Id,x.Name,x.Enabled,x.Provider,x.ModelName,x.EmbeddingProvider,x.EmbeddingModel,x.EmbeddingDimensions,x.SystemPrompt,x.WelcomeMessage,x.FallbackMessage,x.MaxContextChunks,x.MinimumSimilarity,x.Temperature);}
public sealed class UpdateAgentSettingsCommandHandler(IApplicationDbContext db,TimeProvider clock):IRequestHandler<UpdateAgentSettingsCommand,AgentSettingsResult>{public async Task<AgentSettingsResult> HandleAsync(UpdateAgentSettingsCommand r,CancellationToken ct=default){var x=await db.AgentSettings.SingleOrDefaultAsync(x=>x.Name=="portfolio-agent",ct)??throw new NotFoundException("AGENT_SETTINGS_NOT_FOUND","Agent settings were not found.");x.Enabled=r.Enabled;x.Provider=Trim(r.Provider);x.ModelName=Trim(r.ModelName);x.EmbeddingProvider=Trim(r.EmbeddingProvider);x.EmbeddingModel=Trim(r.EmbeddingModel);x.SystemPrompt=r.SystemPrompt.Trim();x.WelcomeMessage=Trim(r.WelcomeMessage);x.FallbackMessage=Trim(r.FallbackMessage);x.MaxContextChunks=r.MaxContextChunks;x.MinimumSimilarity=r.MinimumSimilarity;x.Temperature=r.Temperature;x.UpdatedAt=clock.GetUtcNow();await db.SaveChangesAsync(ct);return GetAgentSettingsQueryHandler.Map(x);}private static string? Trim(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();}
public sealed class UpdateAgentSettingsCommandValidator:IRequestValidator<UpdateAgentSettingsCommand>{public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(UpdateAgentSettingsCommand r,CancellationToken ct=default){var e=new List<ValidationFailure>();if(string.IsNullOrWhiteSpace(r.SystemPrompt))e.Add(new("systemPrompt","System prompt is required."));if(r.SystemPrompt?.Length>10000)e.Add(new("systemPrompt","System prompt must not exceed 10000 characters."));if(r.MaxContextChunks is<1 or>20)e.Add(new("maxContextChunks","Max context chunks must be between 1 and 20."));if(r.MinimumSimilarity is<0 or>1)e.Add(new("minimumSimilarity","Minimum similarity must be between 0 and 1."));if(r.Temperature is<0 or>2)e.Add(new("temperature","Temperature must be between 0 and 2."));foreach(var (n,v,m) in new[]{("provider",r.Provider,100),("modelName",r.ModelName,150),("embeddingProvider",r.EmbeddingProvider,100),("embeddingModel",r.EmbeddingModel,150)})if(v?.Length>m)e.Add(new(n,$"{n} must not exceed {m} characters."));return Task.FromResult<IReadOnlyCollection<ValidationFailure>>(e);}}

public sealed record KnowledgeListItem(Guid Id,string SourceType,Guid? SourceRefId,string SourceKey,string Title,int Version,string IndexingStatus,int ChunkCount,DateTimeOffset? IndexedAt,DateTimeOffset UpdatedAt,string? LastIndexError);
public sealed record KnowledgeChunkResult(Guid Id,int ChunkIndex,string Content,int? TokenCount,string EmbeddingModel);
public sealed record KnowledgeDetail(Guid Id,string SourceType,Guid? SourceRefId,string SourceKey,string Title,string Content,string ContentHash,int Version,string IndexingStatus,DateTimeOffset? IndexedAt,string? LastIndexError,IReadOnlyCollection<KnowledgeChunkResult> Chunks);
public sealed record GetKnowledgeQuery(int Page=1,int PageSize=20,string? SourceType=null,string? Status=null,string? Search=null):IRequest<PagedResult<KnowledgeListItem>>;
public sealed record GetKnowledgeDocumentQuery(Guid Id):IRequest<KnowledgeDetail>;
public sealed record ReindexKnowledgeCommand(Guid Id):IRequest<string>;
public sealed record ReindexAllKnowledgeCommand:IRequest<string>;
public sealed class GetKnowledgeQueryHandler(IApplicationDbContext db):IRequestHandler<GetKnowledgeQuery,PagedResult<KnowledgeListItem>>{public async Task<PagedResult<KnowledgeListItem>> HandleAsync(GetKnowledgeQuery r,CancellationToken ct=default){var q=db.KnowledgeDocuments.AsNoTracking();if(!string.IsNullOrWhiteSpace(r.SourceType)){var v=r.SourceType.Trim().ToUpper();q=q.Where(x=>x.SourceType==v);}if(!string.IsNullOrWhiteSpace(r.Status)){var v=r.Status.Trim().ToUpper();q=q.Where(x=>x.IndexingStatus==v);}if(!string.IsNullOrWhiteSpace(r.Search)){var v=r.Search.Trim().ToLower();q=q.Where(x=>x.Title.ToLower().Contains(v)||x.SourceKey.ToLower().Contains(v));}var total=await q.CountAsync(ct);var items=await q.OrderByDescending(x=>x.UpdatedAt).ThenBy(x=>x.Id).Skip((r.Page-1)*r.PageSize).Take(r.PageSize).Select(x=>new KnowledgeListItem(x.Id,x.SourceType,x.SourceRefId,x.SourceKey,x.Title,x.Version,x.IndexingStatus,db.KnowledgeChunks.Count(c=>c.KnowledgeDocumentId==x.Id),x.IndexedAt,x.UpdatedAt,x.LastIndexError)).ToListAsync(ct);return new(items,r.Page,r.PageSize,total);}}
public sealed class GetKnowledgeDocumentQueryHandler(IApplicationDbContext db):IRequestHandler<GetKnowledgeDocumentQuery,KnowledgeDetail>{public async Task<KnowledgeDetail> HandleAsync(GetKnowledgeDocumentQuery r,CancellationToken ct=default){var x=await db.KnowledgeDocuments.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==r.Id,ct)??throw new NotFoundException("KNOWLEDGE_DOCUMENT_NOT_FOUND","Knowledge document was not found.");var chunks=await db.KnowledgeChunks.AsNoTracking().Where(c=>c.KnowledgeDocumentId==x.Id).OrderBy(c=>c.ChunkIndex).Select(c=>new KnowledgeChunkResult(c.Id,c.ChunkIndex,c.Content,c.TokenCount,c.EmbeddingModel)).ToListAsync(ct);return new(x.Id,x.SourceType,x.SourceRefId,x.SourceKey,x.Title,x.Content,x.ContentHash,x.Version,x.IndexingStatus,x.IndexedAt,x.LastIndexError,chunks);}}
public sealed class ReindexKnowledgeCommandHandler(IApplicationDbContext db):IRequestHandler<ReindexKnowledgeCommand,string>{public async Task<string> HandleAsync(ReindexKnowledgeCommand r,CancellationToken ct=default){var x=await db.KnowledgeDocuments.SingleOrDefaultAsync(x=>x.Id==r.Id,ct)??throw new NotFoundException("KNOWLEDGE_DOCUMENT_NOT_FOUND","Knowledge document was not found.");x.IndexingStatus="PENDING";x.LastIndexError=null;x.IsActive=true;await db.SaveChangesAsync(ct);return "PENDING";}}
public sealed class ReindexAllKnowledgeCommandHandler(IApplicationDbContext db,PortfolioKnowledgeBuilder builder,TimeProvider clock):IRequestHandler<ReindexAllKnowledgeCommand,string>{public async Task<string> HandleAsync(ReindexAllKnowledgeCommand r,CancellationToken ct=default){var sources=await builder.BuildAsync(ct);var keys=sources.Select(x=>x.SourceKey).ToHashSet();var existing=await db.KnowledgeDocuments.ToListAsync(ct);foreach(var stale in existing.Where(x=>x.SourceType!="MANUAL"&&!keys.Contains(x.SourceKey))){stale.IsActive=false;stale.IndexingStatus="PENDING";}foreach(var s in sources){var x=existing.SingleOrDefault(x=>x.SourceKey==s.SourceKey);if(x is null){x=new(){Id=Guid.NewGuid(),SourceType=s.SourceType,SourceRefId=s.SourceRefId,SourceKey=s.SourceKey,Title=s.Title,Content=s.Content,ContentHash=s.ContentHash,SourceUpdatedAt=s.UpdatedAt,Version=1,Metadata=JsonDocument.Parse(s.Metadata),IsActive=true,IndexingStatus="PENDING",IndexedAt=null,LastIndexError=null,CreatedAt=clock.GetUtcNow(),UpdatedAt=clock.GetUtcNow()};db.KnowledgeDocuments.Add(x);continue;}if(x.ContentHash==s.ContentHash&&x.IsActive){continue;}x.Version++;x.SourceType=s.SourceType;x.SourceRefId=s.SourceRefId;x.SourceKey=s.SourceKey;x.Title=s.Title;x.Content=s.Content;x.ContentHash=s.ContentHash;x.SourceUpdatedAt=s.UpdatedAt;x.Metadata=JsonDocument.Parse(s.Metadata);x.IsActive=true;x.IndexingStatus="PENDING";x.IndexedAt=null;x.LastIndexError=null;x.UpdatedAt=clock.GetUtcNow();}await db.SaveChangesAsync(ct);return "PENDING";}}
public sealed class KnowledgeQueryValidator:IRequestValidator<GetKnowledgeQuery>{public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(GetKnowledgeQuery r,CancellationToken ct=default){var e=new List<ValidationFailure>();if(r.Page<1)e.Add(new("page","Page must be at least 1."));if(r.PageSize is<1 or>100)e.Add(new("pageSize","Page size must be between 1 and 100."));var types=new[]{"PROFILE","EXPERIENCE","PROJECT","SKILLS","EDUCATION","TRAINING","CERTIFICATE","JOURNEY","MANUAL"};if(r.SourceType is not null&&!types.Contains(r.SourceType.Trim().ToUpper()))e.Add(new("sourceType","Source type is invalid."));var statuses=new[]{"PENDING","INDEXING","INDEXED","FAILED"};if(r.Status is not null&&!statuses.Contains(r.Status.Trim().ToUpper()))e.Add(new("status","Status is invalid."));return Task.FromResult<IReadOnlyCollection<ValidationFailure>>(e);}}

public sealed record KnowledgeSource(string SourceType,Guid? SourceRefId,string SourceKey,string Title,string Content,string ContentHash,DateTimeOffset? UpdatedAt,string Metadata);
public sealed class PortfolioKnowledgeBuilder(IApplicationDbContext db)
{
    public async Task<IReadOnlyCollection<KnowledgeSource>> BuildAsync(CancellationToken ct=default){var list=new List<KnowledgeSource>();var profile=await db.Profiles.AsNoTracking().SingleOrDefaultAsync(x=>x.IsPublished,ct);if(profile is not null){var links=await db.SocialLinks.AsNoTracking().Where(x=>x.IsVisible).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).Select(x=>x.Platform+": "+x.Url).ToListAsync(ct);Add(list,"PROFILE",profile.Id,"profile:main",profile.FullName,Join($"Name: {profile.FullName}",$"Professional title: {profile.ProfessionalTitle}",$"Headline: {profile.HeroHeadline}",profile.HeroSummary,profile.AboutMarkdown,$"Location: {profile.Location}",$"Education: {profile.University} — {profile.Major}",string.Join("\n",links)),profile.UpdatedAt,"/");}
    var exps=await db.Experiences.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct);foreach(var x in exps){var tech=await db.ExperienceTechnologies.AsNoTracking().Where(t=>t.ExperienceId==x.Id&&t.Technology.IsActive).OrderBy(t=>t.DisplayOrder).Select(t=>t.Technology.Name).ToListAsync(ct);Add(list,"EXPERIENCE",x.Id,$"experience:{x.Id}",$"{x.CompanyName} — {x.RoleTitle}",Join($"Company: {x.CompanyName}",$"Role: {x.RoleTitle}",$"Location: {x.Location}",$"Dates: {x.StartDate} to {(x.IsCurrent?"Present":x.EndDate?.ToString())}",x.Summary,x.ResponsibilitiesMarkdown,$"Technologies: {string.Join(", ",tech)}"),x.UpdatedAt,"/experience");}
    var projects=await db.Projects.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct);foreach(var x in projects){var tech=await db.ProjectTechnologies.AsNoTracking().Where(t=>t.ProjectId==x.Id&&t.Technology.IsActive).OrderBy(t=>t.DisplayOrder).Select(t=>t.Technology.Name).ToListAsync(ct);var sectionEntities=await db.ProjectSections.AsNoTracking().Where(s=>s.ProjectId==x.Id&&s.IsVisible).OrderBy(s=>s.DisplayOrder).ThenBy(s=>s.Id).ToListAsync(ct);var sections=sectionEntities.Select(s=>Join(s.Title,s.Subtitle,s.ContentMarkdown,s.ContentJson.RootElement.GetRawText()));Add(list,"PROJECT",x.Id,$"project:{x.Slug}",x.Title,Join($"Project: {x.Title}",x.Subtitle,x.ShortDescription,x.OverviewMarkdown,$"Role: {x.Role}",$"Status: {x.Status}",$"Technologies: {string.Join(", ",tech)}",string.Join("\n\n",sections),$"GitHub: {x.GithubUrl}",$"Live: {x.LiveUrl}"),x.UpdatedAt,$"/projects/{x.Slug}",x.Slug);}
    var skills=await db.Skills.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct);if(skills.Count>0)Add(list,"SKILLS",null,"skills:all","Technical skills",string.Join("\n",skills.Select(x=>$"{x.Name} — {x.Category} — {x.ExperienceLevel}. {x.Description}")),skills.Max(x=>x.UpdatedAt),"/skills");
    foreach(var x in await db.Educations.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct))Add(list,"EDUCATION",x.Id,$"education:{x.Id}",x.Institution,Join($"Institution: {x.Institution}",$"Degree: {x.Degree}",$"Field: {x.FieldOfStudy}",$"Dates: {x.StartDate} to {x.EndDate}",x.Description,$"Location: {x.Location}"),x.UpdatedAt,"/experience");
    foreach(var x in await db.Trainings.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct))Add(list,"TRAINING",x.Id,$"training:{x.Id}",x.Title,Join($"Training: {x.Title}",$"Provider: {x.Provider}",x.Description,$"Dates: {x.StartDate} to {x.EndDate}",$"Credential: {x.CredentialUrl}"),x.UpdatedAt,"/experience");
    foreach(var x in await db.Certificates.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct))Add(list,"CERTIFICATE",x.Id,$"certificate:{x.Id}",x.Name,Join($"Certificate: {x.Name}",$"Issuer: {x.Issuer}",$"Issued: {x.IssuedAt}",$"Expires: {x.ExpiresAt}",$"Credential: {x.CredentialUrl}"),x.UpdatedAt,"/");
    foreach(var x in await db.JourneyItems.AsNoTracking().Where(x=>x.IsPublished).OrderBy(x=>x.DisplayOrder).ThenBy(x=>x.Id).ToListAsync(ct))Add(list,"JOURNEY",x.Id,$"journey:{x.Id}",x.Title,Join($"Journey: {x.Title}",x.Subtitle,x.Description,$"Date: {x.OccurredAt}"),x.UpdatedAt,"/journey");return list;}
    private static string Join(params string?[] values)=>string.Join("\n",values.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x!.Trim()));private static void Add(List<KnowledgeSource> list,string type,Guid? id,string key,string title,string content,DateTimeOffset? updated,string url,string? slug=null){var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant();list.Add(new(type,id,key,title,content,hash,updated,JsonSerializer.Serialize(new{publicUrl=url,projectSlug=slug})));}
}

public static class KnowledgeChunker{public static IReadOnlyList<string> Chunk(string content,int maxChars=1200,int overlap=150){var paragraphs=content.Replace("\r","").Split("\n\n",StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries);var chunks=new List<string>();var current=new StringBuilder();foreach(var p0 in paragraphs){var p=p0;while(p.Length>maxChars){if(current.Length>0){chunks.Add(current.ToString());current.Clear();}chunks.Add(p[..maxChars]);p=p[Math.Max(1,maxChars-overlap)..];}if(current.Length+p.Length+2>maxChars&&current.Length>0){var done=current.ToString();chunks.Add(done);current.Clear();if(overlap>0)current.Append(done[^Math.Min(overlap,done.Length)..]).Append("\n\n");}current.Append(p).Append("\n\n");}if(current.Length>0)chunks.Add(current.ToString().Trim());return chunks;}}
