import { PortfolioAggregate, PublicProjectDetail, PublicProjectListItem } from './public.models';

export const project: PublicProjectListItem = { id: 'p1', slug: 'real-project', title: 'API project', subtitle: null, shortDescription: 'Published summary', role: 'Developer', status: 'COMPLETED', featured: true, thumbnailUrl: null, technologies: [{ id: 't1', name: 'Angular', category: 'Frontend' }] };
export const portfolio: PortfolioAggregate = {
  profile: { fullName: 'API Person', professionalTitle: 'Engineer', secondaryTitle: null, heroHeadline: 'Building useful systems', heroSummary: 'Real API summary', aboutMarkdown: null, email: null, location: null, university: null, major: null, availabilityStatus: null, profileImageUrl: null, cvUrl: null },
  experiences: [{ id: 'e1', companyName: 'API Company', roleTitle: 'Engineer', location: null, startDate: '2024-01-01', endDate: null, isCurrent: true, summary: null, responsibilitiesMarkdown: null, companyUrl: null, technologies: [] }],
  featuredProjects: [project], skills: [{ id: 's1', name: 'TypeScript', category: 'Languages', experienceLevel: 'USED', description: null, technologyId: null }, { id: 's2', name: 'Angular', category: 'Frontend', experienceLevel: 'LEARNING', description: null, technologyId: 't1' }],
  educations: [{ id: 'ed1', institution: 'API University', degree: null, fieldOfStudy: null, startDate: null, endDate: null, description: null, location: null }], trainings: [{ id: 'tr1', title: 'API Training', provider: null, description: null, startDate: null, endDate: null, credentialUrl: null }], certificates: [{ id: 'c1', name: 'API Certificate', issuer: null, issuedAt: null, expiresAt: null, credentialId: null, credentialUrl: null, certificateUrl: null }],
  journey: [{ id: 'j1', title: 'First milestone', subtitle: null, description: null, occurredAt: '2023-01-01', iconKey: null }, { id: 'j2', title: 'Second milestone', subtitle: null, description: null, occurredAt: null, iconKey: null }], socialLinks: [],
};
export const projectDetail: PublicProjectDetail = { ...project, overviewMarkdown: 'Overview', teamSize: 2, startDate: '2024-01-01', endDate: null, githubUrl: 'https://example.com/repo', liveUrl: 'javascript:alert(1)', seo: { title: null, description: null }, sections: [{ id: 'sec2', sectionType: 'TEXT', title: 'Second', subtitle: null, contentMarkdown: 'Body', content: null, displayOrder: 2 }, { id: 'sec1', sectionType: 'TEXT', title: 'First', subtitle: null, contentMarkdown: null, content: { text: 'Structured text' }, displayOrder: 1 }], media: [{ id: 'm2', role: 'GALLERY', url: 'https://example.com/two.png', altText: null, caption: 'Second media', displayOrder: 2 }, { id: 'm1', role: 'GALLERY', url: 'https://example.com/one.png', altText: 'First', caption: 'First media', displayOrder: 1 }] };
