import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { finalize, take } from 'rxjs';
import { safeAdminError } from '../shared/admin-api';
import { AdminPageHeaderComponent } from '../shared/admin-page-header.component';
import { MediaAdminService } from './media-admin.service';
import { MediaAsset, MediaType } from './media.models';

@Component({
  selector: 'app-media-library-page', imports: [DatePipe, FormsModule, AdminPageHeaderComponent],
  template: `<div class="admin-page"><app-admin-page-header title="Media library" eyebrow="Website" description="Upload and manage images and documents used throughout the portfolio."/>
  <section class="admin-panel upload"><label>File<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" (change)="choose($event)"/>@if(file()){<small>{{file()!.name}} · {{formatSize(file()!.size)}}</small>}</label><label>Type<select [(ngModel)]="uploadType"><option>IMAGE</option><option>DOCUMENT</option><option>CV</option><option>OTHER</option></select></label><label>Alt text<input [(ngModel)]="uploadAlt" maxlength="500"/></label><button class="admin-button primary" [disabled]="!file()||busy()" (click)="upload()">{{busy()?'Uploading…':'Upload'}}</button></section>
  <div class="filters"><input aria-label="Search media" placeholder="Search filename or alt text" [(ngModel)]="search" (keyup.enter)="load()"/><select aria-label="Filter media type" [(ngModel)]="filter"><option value="">All types</option><option>IMAGE</option><option>DOCUMENT</option><option>CV</option><option>OTHER</option></select><button class="admin-button" (click)="load()">Filter</button></div>
  @if(error()){<p class="admin-error" role="alert">{{error()}}</p>}@if(success()){<p class="admin-success" role="status">{{success()}}</p>}
  @if(loading()){<div class="state-panel" role="status">Loading media…</div>}@else if(items().length===0){<div class="state-panel">No media matches this view.</div>}@else{<div class="grid">@for(x of items();track x.id){<article class="admin-panel card">@if(x.mimeType?.startsWith('image/')){<img [src]="x.publicUrl" [alt]="x.altText||x.fileName"/>}@else{<a [href]="x.publicUrl" target="_blank" rel="noopener">Open {{x.mediaType.toLowerCase()}}</a>}<strong>{{x.fileName}}</strong><small>{{x.mediaType}} · {{formatSize(x.fileSize)}} · {{x.createdAt|date:'mediumDate'}}</small><label>Alt text<input [ngModel]="x.altText" (ngModelChange)="x.altText=$event" maxlength="500"/></label><label>Type<select [(ngModel)]="x.mediaType"><option>IMAGE</option><option>DOCUMENT</option><option>CV</option><option>OTHER</option></select></label><div class="actions"><button class="admin-button" (click)="save(x)">Save</button>@if(confirming()===x.id){<button class="admin-button danger" (click)="remove(x.id)">Confirm delete</button><button class="admin-button" (click)="confirming.set(null)">Cancel</button>}@else{<button class="admin-button danger" (click)="confirming.set(x.id)">Delete</button>}</div></article>}</div>}</div>`,
  styles: `.upload,.filters{display:flex;gap:1rem;align-items:end;flex-wrap:wrap;margin-bottom:1rem}.filters{margin-top:1rem}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(15rem,1fr));gap:1rem}.card{display:grid;gap:.65rem}.card img{width:100%;aspect-ratio:16/10;object-fit:cover;border-radius:var(--radius-md);background:var(--color-surface-high)}.card small,.upload small{display:block;color:var(--color-text-muted)}.actions{display:flex;gap:.5rem;flex-wrap:wrap}`
})
export class MediaLibraryPageComponent {
  private readonly api=inject(MediaAdminService); readonly items=signal<MediaAsset[]>([]); readonly file=signal<File|null>(null); readonly busy=signal(false); readonly loading=signal(true); readonly error=signal<string|null>(null); readonly success=signal<string|null>(null); readonly confirming=signal<string|null>(null); uploadType:MediaType='IMAGE'; uploadAlt=''; filter:''|MediaType=''; search='';
  constructor(){this.load()}
  choose(e:Event){const f=(e.target as HTMLInputElement).files?.[0]??null;this.error.set(null);this.success.set(null);if(f&&(!['image/jpeg','image/png','image/webp','image/gif','application/pdf'].includes(f.type)||f.size>10*1024*1024)){this.file.set(null);this.error.set('Choose a JPEG, PNG, WebP, GIF, or PDF no larger than 10 MiB.');return}this.file.set(f);if(f?.type.startsWith('image/'))this.uploadType='IMAGE';else if(f?.type==='application/pdf'&&this.uploadType==='IMAGE')this.uploadType='DOCUMENT'}
  upload(){const f=this.file();if(!f)return;this.busy.set(true);this.error.set(null);this.api.upload(f,this.uploadType,this.uploadAlt.trim()||null).pipe(take(1),finalize(()=>this.busy.set(false))).subscribe({next:()=>{this.file.set(null);this.uploadAlt='';this.success.set('Media uploaded.');this.load(false)},error:e=>this.error.set(safeAdminError(e))})}
  load(clearSuccess=true){this.loading.set(true);this.error.set(null);if(clearSuccess)this.success.set(null);this.api.list(1,100,this.filter||undefined,this.search).pipe(take(1),finalize(()=>this.loading.set(false))).subscribe({next:x=>this.items.set(x.items),error:e=>this.error.set(safeAdminError(e))})}
  save(x:MediaAsset){this.api.update(x.id,{altText:x.altText?.trim()||null,mediaType:x.mediaType}).pipe(take(1)).subscribe({next:y=>{Object.assign(x,y);this.success.set('Media metadata saved.')},error:e=>this.error.set(safeAdminError(e))})}
  remove(id:string){this.api.delete(id).pipe(take(1)).subscribe({next:()=>{this.confirming.set(null);this.success.set('Media deleted.');this.load(false)},error:e=>this.error.set(safeAdminError(e))})}
  formatSize(n:number|null){return n===null?'Unknown size':`${(n/1024).toFixed(n<10240?1:0)} KiB`}
}
