import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { take } from 'rxjs';
import { LoadingIndicatorComponent } from '../../../shared/components/loading-indicator/loading-indicator.component';
import { AdminEmptyStateComponent } from '../shared/admin-empty-state.component';
import { safeAdminError } from '../shared/admin-api';
import { Dashboard } from '../shared/admin.models';
import { AdminPageHeaderComponent } from '../shared/admin-page-header.component';
import { DashboardService } from './dashboard.service';

@Component({ selector:'app-dashboard-page', imports:[DatePipe,LoadingIndicatorComponent,AdminEmptyStateComponent,AdminPageHeaderComponent], providers:[DashboardService], template:`<div class="admin-page"><app-admin-page-header title="Dashboard" eyebrow="Overview" description="A current summary from the portfolio API." />@if(status()==='loading'){<div class="state-panel"><app-loading-indicator label="Loading dashboard"/></div>}@else if(status()==='error'){<div class="state-panel" role="alert"><p>{{error()}}</p><button class="admin-button" (click)="load()">Retry</button></div>}@else if(data();as d){<section class="metric-grid" aria-label="Portfolio metrics">@for(metric of metrics(d);track metric.label){<article><span>{{metric.label}}</span><strong>{{metric.value}}</strong></article>}</section><section class="admin-panel updates"><h2>Recent updates</h2>@if(d.recentUpdates.length){<ul class="admin-list">@for(item of d.recentUpdates;track item.resourceType+item.id){<li class="admin-list-item"><div><strong>{{item.title}}</strong><p>{{item.resourceType}}</p></div><time [attr.datetime]="item.updatedAt">{{item.updatedAt|date:'medium'}}</time></li>}</ul>}@else{<app-admin-empty-state title="No recent updates" message="Changed portfolio records will appear here."/>}</section>}</div>`, styles:`.metric-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(10rem,1fr));gap:1rem;margin-bottom:2rem}.metric-grid article{padding:1.25rem;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface)}.metric-grid span{display:block;color:var(--color-text-dim);font-size:.75rem}.metric-grid strong{display:block;margin-top:.5rem;font-size:2rem}.updates h2{margin-top:0}.updates p{margin:.25rem 0 0;color:var(--color-text-muted)}time{color:var(--color-text-dim);font-size:.75rem}` })
export class DashboardPageComponent { private api=inject(DashboardService); readonly status=signal<'loading'|'loaded'|'error'>('loading'); readonly data=signal<Dashboard|null>(null); readonly error=signal<string|null>(null); constructor(){this.load()} load(){this.status.set('loading');this.api.get().pipe(take(1)).subscribe({next:x=>{this.data.set(x);this.status.set('loaded')},error:e=>{this.error.set(safeAdminError(e,'Unable to load dashboard.'));this.status.set('error')}})} metrics(d:Dashboard){return[{label:'Projects',value:d.projects},{label:'Experiences',value:d.experiences},{label:'Skills',value:d.skills},{label:'Certificates',value:d.certificates},{label:'Knowledge indexed',value:d.knowledge.indexed},{label:'Knowledge pending',value:d.knowledge.pending},{label:'Knowledge failed',value:d.knowledge.failed},{label:'Conversations',value:d.conversations}]}}
