import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { take } from 'rxjs';
import { LoadingIndicatorComponent } from '../../../shared/components/loading-indicator/loading-indicator.component';
import { AdminEmptyStateComponent } from '../shared/admin-empty-state.component';
import { safeAdminError } from '../shared/admin-api';
import { ContactMessage, ContactStatus } from '../shared/admin.models';
import { AdminPageHeaderComponent } from '../shared/admin-page-header.component';
import { ContactMessageAdminService } from './contact-message-admin.service';

@Component({ selector:'app-contact-message-list-page', imports:[DatePipe,FormsModule,RouterLink,LoadingIndicatorComponent,AdminEmptyStateComponent,AdminPageHeaderComponent], providers:[ContactMessageAdminService], template:`<div class="admin-page"><app-admin-page-header title="Contact Messages" eyebrow="Inbox"><label>Status <select class="admin-input" [ngModel]="status()" (ngModelChange)="filter($event)"><option value="">All</option>@for(x of statuses;track x){<option [value]="x">{{x}}</option>}</select></label></app-admin-page-header>@if(loading()){<div class="state-panel"><app-loading-indicator label="Loading messages"/></div>}@else if(error()){<p class="admin-error" role="alert">{{error()}}</p>}@else if(!items().length){<app-admin-empty-state title="No messages" message="No contact messages match this filter."/>}@else{<div class="table-wrap"><table class="admin-table"><thead><tr><th>Status</th><th>Sender</th><th>Subject</th><th>Received</th><th></th></tr></thead><tbody>@for(x of items();track x.id){<tr><td><span class="status-badge">{{x.status}}</span></td><td>{{x.name}}<br/><small>{{x.email}}</small></td><td>{{x.subject||'No subject'}}</td><td>{{x.receivedAt|date:'medium'}}</td><td><a class="admin-button" [routerLink]="[x.id]">View</a></td></tr>}</tbody></table></div><nav class="pagination" aria-label="Message pages"><button class="admin-button" [disabled]="page()===1" (click)="go(page()-1)">Previous</button><span>Page {{page()}} of {{totalPages()}}</span><button class="admin-button" [disabled]="page()===totalPages()" (click)="go(page()+1)">Next</button></nav>}</div>`, styles:`small{color:var(--color-text-dim)}.pagination{display:flex;justify-content:center;align-items:center;gap:1rem;margin-top:1.5rem}` })
export class ContactMessageListPageComponent { private api=inject(ContactMessageAdminService); readonly statuses:ContactStatus[]=['NEW','READ','REPLIED','ARCHIVED']; readonly items=signal<ContactMessage[]>([]); readonly page=signal(1); readonly totalPages=signal(1); readonly status=signal(''); readonly loading=signal(true); readonly error=signal<string|null>(null); constructor(){this.load()} filter(status:string){this.status.set(status);this.page.set(1);this.load()} go(page:number){this.page.set(page);this.load()} load(){this.loading.set(true);this.api.list(this.page(),20,this.status()||undefined).pipe(take(1)).subscribe({next:x=>{this.items.set(x.items);this.totalPages.set(Math.max(1,x.totalPages));this.loading.set(false)},error:e=>{this.error.set(safeAdminError(e));this.loading.set(false)}})}}
