// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("admin_refresh_tokens_pkey");

                    b.HasAlternateKey("TokenHash")
                        .HasName("uq_admin_refresh_tokens_hash");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_refresh_tokens_user");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_admin_refresh_tokens_expires");

                    b.HasIndex("AdminUserId", "ExpiresAt")
                        .HasDatabaseName("ix_admin_refresh_tokens_active")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("admin_refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_refresh_token_expiry", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("admin_users_pkey");

                    b.HasAlternateKey("Email")
                        .HasName("uq_admin_users_email");

                    b.ToTable("admin_users", null, t =>
                        {
                            t.HasTrigger("trg_admin_users_updated_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AgentSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EmbeddingDimensions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1536)
                        .HasColumnName("embedding_dimensions");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("EmbeddingProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_provider");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("FallbackMessage")
                        .HasColumnType("text")
                        .HasColumnName("fallback_message");

                    b.Property<int>("MaxContextChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("max_context_chunks");

                    b.Property<decimal?>("MinimumSimilarity")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("minimum_similarity");

                    b.Property<string>("ModelName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("portfolio-agent")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<decimal>("Temperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(4,3)")
                        .HasDefaultValue(0.2m)
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text")
                        .HasColumnName("welcome_message");

                    b.HasKey("Id")
                        .HasName("agent_settings_pkey");

                    b.HasAlternateKey("Name")
                        .HasName("uq_agent_settings_name");

                    b.ToTable("agent_settings", null, t =>
                        {
                            t.HasTrigger("trg_agent_settings_updated_at");

                            t.HasCheckConstraint("ck_agent_context_chunks", "max_context_chunks BETWEEN 1 AND 20");

                            t.HasCheckConstraint("ck_agent_embedding_dimensions", "embedding_dimensions = 1536");

                            t.HasCheckConstraint("ck_agent_similarity", "minimum_similarity IS NULL OR minimum_similarity BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_agent_temperature", "temperature BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CertificateMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("certificate_media_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("credential_id");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text")
                        .HasColumnName("credential_url");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<DateOnly?>("IssuedAt")
                        .HasColumnType("date")
                        .HasColumnName("issued_at");

                    b.Property<string>("Issuer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("issuer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("certificates_pkey");

                    b.HasIndex("IsPublished", "DisplayOrder")
                        .HasDatabaseName("ix_certificates_public_order");

                    b.ToTable("certificates", null, t =>
                        {
                            t.HasTrigger("trg_certificates_updated_at");

                            t.HasCheckConstraint("ck_certificates_dates", "expires_at IS NULL OR issued_at IS NULL OR expires_at >= issued_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_session_id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model_name");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("chat_messages_pkey");

                    b.HasIndex("ChatSessionId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_session_created");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_completion_tokens", "completion_tokens IS NULL OR completion_tokens >= 0");

                            t.HasCheckConstraint("ck_chat_messages_latency", "latency_ms IS NULL OR latency_ms >= 0");

                            t.HasCheckConstraint("ck_chat_messages_prompt_tokens", "prompt_tokens IS NULL OR prompt_tokens >= 0");

                            t.HasCheckConstraint("ck_chat_messages_role", "role IN ('USER', 'ASSISTANT', 'SYSTEM')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessageFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_message_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("chat_message_feedback_pkey");

                    b.HasAlternateKey("ChatMessageId")
                        .HasName("uq_chat_message_feedback_message");

                    b.ToTable("chat_message_feedback", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_message_feedback_rating", "rating IN ('POSITIVE', 'NEGATIVE')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessageSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("KnowledgeChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_chunk_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<decimal?>("SimilarityScore")
                        .HasColumnType("numeric(8,7)")
                        .HasColumnName("similarity_score");

                    b.HasKey("Id")
                        .HasName("chat_message_sources_pkey");

                    b.HasAlternateKey("ChatMessageId", "KnowledgeChunkId")
                        .HasName("uq_chat_message_sources");

                    b.HasIndex("ChatMessageId", "Rank")
                        .HasDatabaseName("ix_chat_message_sources_message_rank");

                    b.ToTable("chat_message_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_message_sources_rank", "rank >= 1");

                            t.HasCheckConstraint("ck_chat_message_sources_similarity", "similarity_score IS NULL OR similarity_score BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<int>("MessageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("message_count");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid>("PublicSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_session_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("chat_sessions_pkey");

                    b.HasAlternateKey("PublicSessionId")
                        .HasName("uq_chat_sessions_public_session_id");

                    b.HasIndex("Status", "LastMessageAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_chat_sessions_status_last_message");

                    b.ToTable("chat_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_sessions_message_count", "message_count >= 0");

                            t.HasCheckConstraint("ck_chat_sessions_status", "status IN ('ACTIVE', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("RepliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("replied_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("NEW")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("contact_messages_pkey");

                    b.HasIndex("Status", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_contact_messages_status_received");

                    b.ToTable("contact_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_contact_messages_status", "status IN ('NEW', 'READ', 'REPLIED', 'ARCHIVED')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Degree")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("degree");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("field_of_study");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("institution");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("educations_pkey");

                    b.HasIndex("IsPublished", "DisplayOrder")
                        .HasDatabaseName("ix_educations_public_order");

                    b.ToTable("educations", null, t =>
                        {
                            t.HasTrigger("trg_educations_updated_at");

                            t.HasCheckConstraint("ck_educations_dates", "end_date IS NULL OR start_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanyUrl")
                        .HasColumnType("text")
                        .HasColumnName("company_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("ResponsibilitiesMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("responsibilities_markdown");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role_title");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("experiences_pkey");

                    b.HasIndex("IsPublished", "DisplayOrder")
                        .HasDatabaseName("ix_experiences_public_order");

                    b.ToTable("experiences", null, t =>
                        {
                            t.HasTrigger("trg_experiences_updated_at");

                            t.HasCheckConstraint("ck_experiences_current", "NOT is_current OR end_date IS NULL");

                            t.HasCheckConstraint("ck_experiences_dates", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ExperienceTechnology", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.HasKey("ExperienceId", "TechnologyId")
                        .HasName("experience_technologies_pkey");

                    b.ToTable("experience_technologies", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.JourneyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<DateOnly?>("OccurredAt")
                        .HasColumnType("date")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("journey_items_pkey");

                    b.HasIndex("IsPublished", "DisplayOrder")
                        .HasDatabaseName("ix_journey_items_public_order");

                    b.ToTable("journey_items", null, t =>
                        {
                            t.HasTrigger("trg_journey_items_updated_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("embedding_model");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_document_id");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("knowledge_chunks_pkey");

                    b.HasAlternateKey("KnowledgeDocumentId", "ChunkIndex")
                        .HasName("uq_knowledge_chunks_index");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_chunks_embedding_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("KnowledgeDocumentId", "ChunkIndex")
                        .HasDatabaseName("ix_knowledge_chunks_document");

                    b.ToTable("knowledge_chunks", null, t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_chunks_index", "chunk_index >= 0");

                            t.HasCheckConstraint("ck_knowledge_chunks_tokens", "token_count IS NULL OR token_count >= 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("IndexingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("indexing_status");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastIndexError")
                        .HasColumnType("text")
                        .HasColumnName("last_index_error");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_key");

                    b.Property<Guid?>("SourceRefId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("knowledge_documents_pkey");

                    b.HasAlternateKey("SourceKey")
                        .HasName("uq_knowledge_documents_source_key");

                    b.HasIndex("IndexingStatus", "UpdatedAt")
                        .HasDatabaseName("ix_knowledge_documents_index_queue")
                        .HasFilter("is_active = TRUE AND indexing_status IN ('PENDING', 'FAILED')");

                    b.HasIndex("SourceType", "SourceRefId")
                        .HasDatabaseName("ix_knowledge_documents_source");

                    b.ToTable("knowledge_documents", null, t =>
                        {
                            t.HasTrigger("trg_knowledge_documents_updated_at");

                            t.HasCheckConstraint("ck_knowledge_documents_version", "version >= 1");

                            t.HasCheckConstraint("ck_knowledge_indexing_status", "indexing_status IN ('PENDING', 'INDEXING', 'INDEXED', 'FAILED')");

                            t.HasCheckConstraint("ck_knowledge_source_type", "source_type IN ('PROFILE', 'EXPERIENCE', 'PROJECT', 'SKILLS', 'EDUCATION', 'TRAINING', 'CERTIFICATE', 'JOURNEY', 'MANUAL')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("IMAGE")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("mime_type");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_url");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("media_assets_pkey");

                    b.HasAlternateKey("StorageKey")
                        .HasName("uq_media_assets_storage_key");

                    b.ToTable("media_assets", null, t =>
                        {
                            t.HasTrigger("trg_media_assets_updated_at");

                            t.HasCheckConstraint("ck_media_assets_file_size", "file_size IS NULL OR file_size >= 0");

                            t.HasCheckConstraint("ck_media_assets_type", "media_type IN ('IMAGE', 'DOCUMENT', 'CV', 'OTHER')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AboutMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("about_markdown");

                    b.Property<string>("AvailabilityStatus")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("availability_status");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CvMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cv_media_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("HeroHeadline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hero_headline");

                    b.Property<string>("HeroSummary")
                        .HasColumnType("text")
                        .HasColumnName("hero_summary");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("major");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfessionalTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("professional_title");

                    b.Property<Guid?>("ProfileImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_image_id");

                    b.Property<string>("SecondaryTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("secondary_title");

                    b.Property<short>("SingletonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("singleton_key");

                    b.Property<string>("University")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("university");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.HasAlternateKey("SingletonKey")
                        .HasName("uq_profiles_singleton");

                    b.ToTable("profiles", null, t =>
                        {
                            t.HasTrigger("trg_profiles_updated_at");

                            t.HasCheckConstraint("ck_profiles_singleton", "singleton_key = 1");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("featured");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("LiveUrl")
                        .HasColumnType("text")
                        .HasColumnName("live_url");

                    b.Property<string>("OverviewMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("overview_markdown");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("role");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("seo_description");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seo_title");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("slug");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("COMPLETED")
                        .HasColumnName("status");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtitle");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("integer")
                        .HasColumnName("team_size");

                    b.Property<Guid?>("ThumbnailMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("thumbnail_media_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("projects_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("uq_projects_slug");

                    b.HasIndex("IsPublished", "Featured", "DisplayOrder")
                        .HasDatabaseName("ix_projects_public");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasTrigger("trg_projects_updated_at");

                            t.HasCheckConstraint("ck_projects_dates", "end_date IS NULL OR start_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_projects_status", "status IN ('PLANNED', 'IN_PROGRESS', 'ACTIVE', 'COMPLETED', 'ARCHIVED')");

                            t.HasCheckConstraint("ck_projects_team_size", "team_size IS NULL OR team_size > 0");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("MediaRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SCREENSHOT")
                        .HasColumnName("media_role");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("project_media_pkey");

                    b.HasAlternateKey("ProjectId", "MediaAssetId", "MediaRole")
                        .HasName("uq_project_media");

                    b.HasIndex("ProjectId", "MediaRole", "DisplayOrder")
                        .HasDatabaseName("ix_project_media_order");

                    b.ToTable("project_media", null, t =>
                        {
                            t.HasCheckConstraint("ck_project_media_role", "media_role IN ('THUMBNAIL', 'SCREENSHOT', 'ARCHITECTURE', 'DIAGRAM', 'OTHER')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<JsonDocument>("ContentJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ContentMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("content_markdown");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("section_type");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtitle");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("project_sections_pkey");

                    b.HasIndex("ProjectId", "DisplayOrder")
                        .HasDatabaseName("ix_project_sections_project_order");

                    b.ToTable("project_sections", null, t =>
                        {
                            t.HasTrigger("trg_project_sections_updated_at");

                            t.HasCheckConstraint("ck_project_sections_type", "section_type IN ('OVERVIEW', 'RESPONSIBILITIES', 'ARCHITECTURE', 'ENGINEERING_FOCUS', 'FEATURES', 'CHALLENGES', 'LEARNINGS', 'SCREENSHOTS', 'CUSTOM')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectTechnology", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.HasKey("ProjectId", "TechnologyId")
                        .HasName("project_technologies_pkey");

                    b.HasIndex("ProjectId", "DisplayOrder")
                        .HasDatabaseName("ix_project_technologies_order");

                    b.ToTable("project_technologies", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("site_settings_pkey");

                    b.ToTable("site_settings", null, t =>
                        {
                            t.HasTrigger("trg_site_settings_updated_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("USED")
                        .HasColumnName("experience_level");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("skills_pkey");

                    b.HasIndex("IsPublished", "Category", "DisplayOrder")
                        .HasDatabaseName("ix_skills_public_category");

                    b.ToTable("skills", null, t =>
                        {
                            t.HasTrigger("trg_skills_updated_at");

                            t.HasCheckConstraint("ck_skills_experience_level", "experience_level IN ('USED', 'LEARNING', 'EXPLORING')");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.SocialLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("social_links_pkey");

                    b.HasIndex("IsVisible", "DisplayOrder")
                        .HasDatabaseName("ix_social_links_visible_order");

                    b.ToTable("social_links", null, t =>
                        {
                            t.HasTrigger("trg_social_links_updated_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("IconKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon_key");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("technologies_pkey");

                    b.HasIndex("Category", "DisplayOrder")
                        .HasDatabaseName("ix_technologies_category");

                    b.ToTable("technologies", null, t =>
                        {
                            t.HasTrigger("trg_technologies_updated_at");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("text")
                        .HasColumnName("credential_url");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("trainings_pkey");

                    b.HasIndex("IsPublished", "DisplayOrder")
                        .HasDatabaseName("ix_trainings_public_order");

                    b.ToTable("trainings", null, t =>
                        {
                            t.HasTrigger("trg_trainings_updated_at");

                            t.HasCheckConstraint("ck_trainings_dates", "end_date IS NULL OR start_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AdminRefreshToken", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.AdminRefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");

                    b.Navigation("ReplacedByToken");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.MediaAsset", "CertificateMedia")
                        .WithMany()
                        .HasForeignKey("CertificateMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CertificateMedia");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessageFeedback", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ChatMessageSource", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.KnowledgeChunk", "KnowledgeChunk")
                        .WithMany()
                        .HasForeignKey("KnowledgeChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("KnowledgeChunk");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ExperienceTechnology", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Experience", "Experience")
                        .WithMany()
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany()
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Profile", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.MediaAsset", "CvMedia")
                        .WithMany()
                        .HasForeignKey("CvMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portfolio.Domain.Entities.MediaAsset", "ProfileImage")
                        .WithMany()
                        .HasForeignKey("ProfileImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CvMedia");

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Project", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.MediaAsset", "ThumbnailMedia")
                        .WithMany()
                        .HasForeignKey("ThumbnailMediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ThumbnailMedia");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectMedia", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectSection", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.ProjectTechnology", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Skill", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
