using System.Linq.Expressions;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Portfolio.Application.Common.Abstractions.Messaging;
using Portfolio.Application.Common.Abstractions.Persistence;
using Portfolio.Application.Common.Abstractions.Validation;
using Portfolio.Application.Common.Exceptions;
using Portfolio.Application.Features.Phase4B;
using Portfolio.Application.Features.PortfolioContent;
using Portfolio.Domain.Entities;

namespace Portfolio.Application.Features.Projects;

public sealed record ProjectTechnologyItem(Guid TechnologyId, int DisplayOrder);
public sealed record ReplaceProjectTechnologiesCommand(Guid ProjectId, IReadOnlyCollection<ProjectTechnologyItem> Items) : IRequest<IReadOnlyCollection<ProjectTechnologyResult>>;
public sealed record GetProjectSectionsQuery(Guid ProjectId) : IRequest<IReadOnlyCollection<ProjectSectionResult>>;
public sealed record CreateProjectSectionCommand(Guid ProjectId, string SectionType, string? Title,
    string? Subtitle, string? ContentMarkdown, JsonElement Content, int DisplayOrder, bool IsVisible) : IRequest<ProjectSectionResult>;
public sealed record UpdateProjectSectionCommand(Guid ProjectId, Guid SectionId, string SectionType,
    string? Title, string? Subtitle, string? ContentMarkdown, JsonElement Content,
    int DisplayOrder, bool IsVisible) : IRequest<ProjectSectionResult>;
public sealed record DeleteProjectSectionCommand(Guid ProjectId, Guid SectionId) : IRequest<bool>;
public sealed record ReorderProjectSectionsCommand(Guid ProjectId, IReadOnlyCollection<ReorderItem> Items) : IRequest<bool>;
public sealed record GetProjectMediaQuery(Guid ProjectId) : IRequest<IReadOnlyCollection<ProjectMediaResult>>;
public sealed record AttachProjectMediaCommand(Guid ProjectId, Guid MediaAssetId, string MediaRole,
    string? Caption, int DisplayOrder) : IRequest<ProjectMediaResult>;
public sealed record UpdateProjectMediaCommand(Guid ProjectId, Guid ProjectMediaId, string MediaRole,
    string? Caption, int DisplayOrder) : IRequest<ProjectMediaResult>;
public sealed record DeleteProjectMediaCommand(Guid ProjectId, Guid ProjectMediaId) : IRequest<bool>;

public sealed class ReplaceProjectTechnologiesCommandHandler(IApplicationDbContext db) : IRequestHandler<ReplaceProjectTechnologiesCommand, IReadOnlyCollection<ProjectTechnologyResult>>
{
    public async Task<IReadOnlyCollection<ProjectTechnologyResult>> HandleAsync(ReplaceProjectTechnologiesCommand r, CancellationToken ct = default)
    { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var ids = r.Items.Select(x => x.TechnologyId).ToArray(); if (await db.Technologies.CountAsync(x => ids.Contains(x.Id), ct) != ids.Length) throw new NotFoundException("TECHNOLOGY_NOT_FOUND", "One or more technologies were not found."); var old = await db.ProjectTechnologies.Where(x => x.ProjectId == r.ProjectId).ToListAsync(ct); db.ProjectTechnologies.RemoveRange(old); db.ProjectTechnologies.AddRange(r.Items.Select(x => new ProjectTechnology { ProjectId = r.ProjectId, TechnologyId = x.TechnologyId, DisplayOrder = x.DisplayOrder })); await db.SaveChangesAsync(ct); return await db.ProjectTechnologies.AsNoTracking().Where(x => x.ProjectId == r.ProjectId).OrderBy(x => x.DisplayOrder).ThenBy(x => x.TechnologyId).Select(x => new ProjectTechnologyResult(x.TechnologyId, x.Technology.Name, x.Technology.Category, x.Technology.IconKey, x.DisplayOrder)).ToListAsync(ct); }
}
public sealed class GetProjectSectionsQueryHandler(IApplicationDbContext db) : IRequestHandler<GetProjectSectionsQuery, IReadOnlyCollection<ProjectSectionResult>>
{ public async Task<IReadOnlyCollection<ProjectSectionResult>> HandleAsync(GetProjectSectionsQuery r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var rows = await db.ProjectSections.AsNoTracking().Where(x => x.ProjectId == r.ProjectId).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Id).ToListAsync(ct); return rows.Select(ProjectRelationMapping.Section).ToList(); } }
public sealed class CreateProjectSectionCommandHandler(IApplicationDbContext db, TimeProvider clock) : IRequestHandler<CreateProjectSectionCommand, ProjectSectionResult>
{ public async Task<ProjectSectionResult> HandleAsync(CreateProjectSectionCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var now = clock.GetUtcNow(); var x = new ProjectSection { Id = Guid.NewGuid(), ProjectId = r.ProjectId, CreatedAt = now, UpdatedAt = now }; ProjectRelationMapping.AssignSection(x, r.SectionType, r.Title, r.Subtitle, r.ContentMarkdown, r.Content, r.DisplayOrder, r.IsVisible); db.ProjectSections.Add(x); await db.SaveChangesAsync(ct); return ProjectRelationMapping.Section(x); } }
public sealed class UpdateProjectSectionCommandHandler(IApplicationDbContext db, TimeProvider clock) : IRequestHandler<UpdateProjectSectionCommand, ProjectSectionResult>
{ public async Task<ProjectSectionResult> HandleAsync(UpdateProjectSectionCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var x = await db.ProjectSections.SingleOrDefaultAsync(x => x.Id == r.SectionId && x.ProjectId == r.ProjectId, ct) ?? throw new NotFoundException("PROJECT_SECTION_NOT_FOUND", "The project section was not found."); ProjectRelationMapping.AssignSection(x, r.SectionType, r.Title, r.Subtitle, r.ContentMarkdown, r.Content, r.DisplayOrder, r.IsVisible); x.UpdatedAt = clock.GetUtcNow(); await db.SaveChangesAsync(ct); return ProjectRelationMapping.Section(x); } }
public sealed class DeleteProjectSectionCommandHandler(IApplicationDbContext db) : IRequestHandler<DeleteProjectSectionCommand, bool>
{ public async Task<bool> HandleAsync(DeleteProjectSectionCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var x = await db.ProjectSections.SingleOrDefaultAsync(x => x.Id == r.SectionId && x.ProjectId == r.ProjectId, ct) ?? throw new NotFoundException("PROJECT_SECTION_NOT_FOUND", "The project section was not found."); db.ProjectSections.Remove(x); await db.SaveChangesAsync(ct); return true; } }
public sealed class ReorderProjectSectionsCommandHandler(IApplicationDbContext db) : IRequestHandler<ReorderProjectSectionsCommand, bool>
{ public async Task<bool> HandleAsync(ReorderProjectSectionsCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var ids = r.Items.Select(x => x.Id).ToArray(); var rows = await db.ProjectSections.Where(x => x.ProjectId == r.ProjectId && ids.Contains(x.Id)).ToListAsync(ct); if (rows.Count != ids.Length) throw new NotFoundException("PROJECT_SECTION_NOT_FOUND", "One or more project sections were not found."); var map = r.Items.ToDictionary(x => x.Id, x => x.DisplayOrder); foreach (var x in rows) x.DisplayOrder = map[x.Id]; await db.SaveChangesAsync(ct); return true; } }
public sealed class GetProjectMediaQueryHandler(IApplicationDbContext db) : IRequestHandler<GetProjectMediaQuery, IReadOnlyCollection<ProjectMediaResult>>
{ public async Task<IReadOnlyCollection<ProjectMediaResult>> HandleAsync(GetProjectMediaQuery r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); return await db.ProjectMedia.AsNoTracking().Where(x => x.ProjectId == r.ProjectId).OrderBy(x => x.DisplayOrder).ThenBy(x => x.Id).Select(ProjectRelationMapping.MediaProjection).ToListAsync(ct); } }
public sealed class AttachProjectMediaCommandHandler(IApplicationDbContext db, TimeProvider clock) : IRequestHandler<AttachProjectMediaCommand, ProjectMediaResult>
{ public async Task<ProjectMediaResult> HandleAsync(AttachProjectMediaCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); if (!await db.MediaAssets.AnyAsync(x => x.Id == r.MediaAssetId, ct)) throw new NotFoundException("MEDIA_NOT_FOUND", "The media asset was not found."); var role = r.MediaRole.Trim().ToUpperInvariant(); if (await db.ProjectMedia.AnyAsync(x => x.ProjectId == r.ProjectId && x.MediaAssetId == r.MediaAssetId && x.MediaRole == role, ct)) throw new ConflictException("PROJECT_MEDIA_EXISTS", "This media association already exists."); var x = new ProjectMedia { Id = Guid.NewGuid(), ProjectId = r.ProjectId, MediaAssetId = r.MediaAssetId, MediaRole = role, Caption = r.Caption?.Trim(), DisplayOrder = r.DisplayOrder, CreatedAt = clock.GetUtcNow() }; db.ProjectMedia.Add(x); await db.SaveChangesAsync(ct); return await ProjectRelationMapping.GetMedia(db, x.Id, ct); } }
public sealed class UpdateProjectMediaCommandHandler(IApplicationDbContext db) : IRequestHandler<UpdateProjectMediaCommand, ProjectMediaResult>
{ public async Task<ProjectMediaResult> HandleAsync(UpdateProjectMediaCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var x = await db.ProjectMedia.SingleOrDefaultAsync(x => x.Id == r.ProjectMediaId && x.ProjectId == r.ProjectId, ct) ?? throw new NotFoundException("PROJECT_MEDIA_NOT_FOUND", "The project media association was not found."); var role = r.MediaRole.Trim().ToUpperInvariant(); if (await db.ProjectMedia.AnyAsync(y => y.Id != x.Id && y.ProjectId == r.ProjectId && y.MediaAssetId == x.MediaAssetId && y.MediaRole == role, ct)) throw new ConflictException("PROJECT_MEDIA_EXISTS", "This media association already exists."); x.MediaRole = role; x.Caption = r.Caption?.Trim(); x.DisplayOrder = r.DisplayOrder; await db.SaveChangesAsync(ct); return await ProjectRelationMapping.GetMedia(db, x.Id, ct); } }
public sealed class DeleteProjectMediaCommandHandler(IApplicationDbContext db) : IRequestHandler<DeleteProjectMediaCommand, bool>
{ public async Task<bool> HandleAsync(DeleteProjectMediaCommand r, CancellationToken ct = default) { await ProjectRelationMapping.RequireProject(db, r.ProjectId, ct); var x = await db.ProjectMedia.SingleOrDefaultAsync(x => x.Id == r.ProjectMediaId && x.ProjectId == r.ProjectId, ct) ?? throw new NotFoundException("PROJECT_MEDIA_NOT_FOUND", "The project media association was not found."); db.ProjectMedia.Remove(x); await db.SaveChangesAsync(ct); return true; } }

public sealed class ReplaceProjectTechnologiesCommandValidator : IRequestValidator<ReplaceProjectTechnologiesCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(ReplaceProjectTechnologiesCommand r, CancellationToken ct = default) { var f = new List<ValidationFailure>(); if (r.Items is null) f.Add(new("items", "Items are required.")); else { if (r.Items.Select(x => x.TechnologyId).Distinct().Count() != r.Items.Count) f.Add(new("items", "Technology IDs must be unique.")); if (r.Items.Any(x => x.DisplayOrder < 0)) f.Add(new("items", "Display order must be non-negative.")); } return Task.FromResult<IReadOnlyCollection<ValidationFailure>>(f); } }
public sealed class CreateProjectSectionCommandValidator : IRequestValidator<CreateProjectSectionCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(CreateProjectSectionCommand r, CancellationToken ct = default) => Task.FromResult<IReadOnlyCollection<ValidationFailure>>(ProjectRelationValidation.Section(r.SectionType, r.Title, r.Subtitle, r.DisplayOrder)); }
public sealed class UpdateProjectSectionCommandValidator : IRequestValidator<UpdateProjectSectionCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(UpdateProjectSectionCommand r, CancellationToken ct = default) => Task.FromResult<IReadOnlyCollection<ValidationFailure>>(ProjectRelationValidation.Section(r.SectionType, r.Title, r.Subtitle, r.DisplayOrder)); }
public sealed class ReorderProjectSectionsCommandValidator : IRequestValidator<ReorderProjectSectionsCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(ReorderProjectSectionsCommand r, CancellationToken ct = default) { var f = new List<ValidationFailure>(); ContentValidation.ReorderItems(f, r.Items); return Task.FromResult<IReadOnlyCollection<ValidationFailure>>(f); } }
public sealed class AttachProjectMediaCommandValidator : IRequestValidator<AttachProjectMediaCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(AttachProjectMediaCommand r, CancellationToken ct = default) => Task.FromResult<IReadOnlyCollection<ValidationFailure>>(ProjectRelationValidation.Media(r.MediaRole, r.Caption, r.DisplayOrder)); }
public sealed class UpdateProjectMediaCommandValidator : IRequestValidator<UpdateProjectMediaCommand>
{ public Task<IReadOnlyCollection<ValidationFailure>> ValidateAsync(UpdateProjectMediaCommand r, CancellationToken ct = default) => Task.FromResult<IReadOnlyCollection<ValidationFailure>>(ProjectRelationValidation.Media(r.MediaRole, r.Caption, r.DisplayOrder)); }
internal static class ProjectRelationValidation
{ private static readonly string[] SectionTypes = ["OVERVIEW", "RESPONSIBILITIES", "ARCHITECTURE", "ENGINEERING_FOCUS", "FEATURES", "CHALLENGES", "LEARNINGS", "SCREENSHOTS", "CUSTOM"]; private static readonly string[] MediaRoles = ["THUMBNAIL", "SCREENSHOT", "ARCHITECTURE", "DIAGRAM", "OTHER"]; public static List<ValidationFailure> Section(string type, string? title, string? subtitle, int order) { var f = new List<ValidationFailure>(); ContentValidation.RequiredText(f, "sectionType", type, 50); if (!string.IsNullOrWhiteSpace(type) && !SectionTypes.Contains(type.Trim().ToUpperInvariant())) f.Add(new("sectionType", "Project section type is invalid.")); ContentValidation.OptionalText(f, "title", title, 255); ContentValidation.OptionalText(f, "subtitle", subtitle, 500); ContentValidation.DisplayOrder(f, order); return f; } public static List<ValidationFailure> Media(string role, string? caption, int order) { var f = new List<ValidationFailure>(); ContentValidation.RequiredText(f, "mediaRole", role, 30); if (!string.IsNullOrWhiteSpace(role) && !MediaRoles.Contains(role.Trim().ToUpperInvariant())) f.Add(new("mediaRole", "Project media role is invalid.")); ContentValidation.OptionalText(f, "caption", caption, 500); ContentValidation.DisplayOrder(f, order); return f; } }
internal static class ProjectRelationMapping
{
    public static readonly Expression<Func<ProjectMedia, ProjectMediaResult>> MediaProjection = x => new(x.Id, x.MediaAssetId, x.MediaRole, x.MediaAsset.PublicUrl, x.MediaAsset.AltText, x.Caption, x.DisplayOrder);
    public static ProjectSectionResult Section(ProjectSection x) => new(x.Id, x.SectionType, x.Title, x.Subtitle, x.ContentMarkdown, x.ContentJson.RootElement.Clone(), x.DisplayOrder, x.IsVisible);
    public static void AssignSection(ProjectSection x, string type, string? title, string? subtitle, string? markdown, JsonElement content, int order, bool visible) { x.SectionType = type.Trim().ToUpperInvariant(); x.Title = title?.Trim(); x.Subtitle = subtitle?.Trim(); x.ContentMarkdown = markdown; x.ContentJson = JsonDocument.Parse(content.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null ? "{}" : content.GetRawText()); x.DisplayOrder = order; x.IsVisible = visible; }
    public static async Task RequireProject(IApplicationDbContext db, Guid id, CancellationToken ct) { if (!await db.Projects.AnyAsync(x => x.Id == id, ct)) throw new NotFoundException("PROJECT_NOT_FOUND", "The project was not found."); }
    public static async Task<ProjectMediaResult> GetMedia(IApplicationDbContext db, Guid id, CancellationToken ct) => await db.ProjectMedia.AsNoTracking().Where(x => x.Id == id).Select(MediaProjection).SingleAsync(ct);
}
