import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { take } from 'rxjs';
import { MediaPickerComponent } from '../media/media-picker.component';
import { MediaAsset } from '../media/media.models';
import { safeAdminError } from '../shared/admin-api';
import { ProjectMedia } from '../shared/admin.models';
import { ProjectAdminService } from './project-admin.service';

@Component({selector:'app-project-media-manager',imports:[FormsModule,MediaPickerComponent],providers:[ProjectAdminService],template:`<section class="admin-panel manager"><h2>Project media</h2>@if(!projectId){<p>Save the project before attaching media.</p>}@else{@if(error()){<p class="admin-error">{{error()}}</p>}<div class="relations">@for(x of items();track x.id){<article><a [href]="x.url" target="_blank" rel="noopener">Open media</a><select aria-label="Media role" [(ngModel)]="x.mediaRole"><option>THUMBNAIL</option><option>SCREENSHOT</option><option>ARCHITECTURE</option><option>DIAGRAM</option><option>OTHER</option></select><input aria-label="Media caption" [(ngModel)]="x.caption" maxlength="500"/><input aria-label="Media display order" type="number" min="0" [(ngModel)]="x.displayOrder"/><button class="admin-button" (click)="saveRelation(x)">Save</button><button class="admin-button danger" (click)="remove(x.id)">Remove</button></article>}</div><label>Role<select [(ngModel)]="role"><option>THUMBNAIL</option><option>SCREENSHOT</option><option>ARCHITECTURE</option><option>DIAGRAM</option><option>OTHER</option></select></label><label>Caption<input [(ngModel)]="caption" maxlength="500"/></label><app-media-picker mediaType="IMAGE" (selected)="attach($event)"/>}</section>`,styles:`.manager{margin-top:1.5rem}.relations{display:grid;gap:.5rem;margin:1rem 0}.relations article{display:flex;gap:.75rem;align-items:center;flex-wrap:wrap}`})
export class ProjectMediaManagerComponent { private readonly api=inject(ProjectAdminService);private readonly route=inject(ActivatedRoute);readonly projectId=this.route.snapshot.paramMap.get('id');readonly items=signal<ProjectMedia[]>([]);readonly error=signal<string|null>(null);role='SCREENSHOT';caption='';constructor(){this.load()}load(){if(this.projectId)this.api.media(this.projectId).pipe(take(1)).subscribe({next:x=>this.items.set(x),error:e=>this.error.set(safeAdminError(e))})}attach(asset:MediaAsset){if(!this.projectId)return;this.api.attachMedia(this.projectId,{mediaAssetId:asset.id,mediaRole:this.role,caption:this.caption.trim()||null,displayOrder:this.items().length}).pipe(take(1)).subscribe({next:()=>{this.caption='';this.load()},error:e=>this.error.set(safeAdminError(e))})}saveRelation(x:ProjectMedia){if(!this.projectId)return;this.api.updateMedia(this.projectId,x.id,{mediaRole:x.mediaRole,caption:x.caption?.trim()||null,displayOrder:x.displayOrder}).pipe(take(1)).subscribe({next:()=>this.load(),error:e=>this.error.set(safeAdminError(e))})}remove(id:string){if(!this.projectId||!window.confirm('Remove this media relation?'))return;this.api.deleteMedia(this.projectId,id).pipe(take(1)).subscribe({next:()=>this.load(),error:e=>this.error.set(safeAdminError(e))})} }
