import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { of, Subject, throwError } from 'rxjs';
import { vi } from 'vitest';
import { CandidateJobPreferences } from './job-hunting.models';
import { JobPreferencesPageComponent } from './job-preferences-page.component';
import { JobHuntingService } from './job-hunting.service';

const preferences=(overrides:Partial<CandidateJobPreferences>={}):CandidateJobPreferences=>({id:null,targetRoles:[],preferredTechnologies:[],acceptableLocations:[],workplaceTypes:[],employmentTypes:[],minimumSalary:null,salaryCurrency:null,salaryPeriod:null,version:0,createdAt:null,updatedAt:null,...overrides});
function mount(api:Record<string,unknown>):ComponentFixture<JobPreferencesPageComponent>{TestBed.configureTestingModule({imports:[JobPreferencesPageComponent],providers:[provideRouter([]),{provide:JobHuntingService,useValue:api}]});const fixture=TestBed.createComponent(JobPreferencesPageComponent);fixture.detectChanges();return fixture}

describe('Job preferences page',()=>{
  afterEach(()=>TestBed.resetTestingModule());
  it('loads the initial no-row state without fabricating preferences',()=>{const fixture=mount({preferences:()=>of(preferences())});expect(fixture.componentInstance.loading()).toBe(false);expect(fixture.componentInstance.form.controls.targetRoles.value).toBe('');expect(fixture.componentInstance.form.pristine).toBe(true)});
  it('loads values and rebinds normalized server values and version after save',()=>{const api={preferences:()=>of(preferences({id:'p1',version:3,targetRoles:['Backend Developer']})),updatePreferences:vi.fn().mockReturnValueOnce(of(preferences({id:'p1',version:4,targetRoles:['Backend Developer','Full Stack Developer'],salaryCurrency:'USD',salaryPeriod:'MONTH',minimumSalary:1000}))).mockReturnValueOnce(of(preferences({id:'p1',version:5,targetRoles:['Backend Developer']})))};const fixture=mount(api);const c=fixture.componentInstance;expect(c.form.controls.targetRoles.value).toBe('Backend Developer');c.form.patchValue({targetRoles:' Full Stack Developer\nBackend Developer\nbackend developer ',minimumSalary:1000,salaryCurrency:'usd',salaryPeriod:'month'});c.form.markAsDirty();c.save();expect(api.updatePreferences).toHaveBeenNthCalledWith(1,expect.objectContaining({expectedVersion:3,targetRoles:['Full Stack Developer','Backend Developer','backend developer']}));expect(c.form.controls.targetRoles.value).toBe('Backend Developer\nFull Stack Developer');expect(c.form.controls.salaryCurrency.value).toBe('USD');expect(c.form.pristine).toBe(true);c.form.patchValue({targetRoles:'Backend Developer'});c.form.markAsDirty();c.save();expect(api.updatePreferences).toHaveBeenNthCalledWith(2,expect.objectContaining({expectedVersion:4}))});
  it('blocks duplicate saves and exposes safe conflict state',()=>{const pending=new Subject<CandidateJobPreferences>();const api={preferences:vi.fn(()=>of(preferences({version:1}))),updatePreferences:vi.fn(()=>pending)};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({targetRoles:'Backend'});c.form.markAsDirty();c.save();c.save();expect(api.updatePreferences).toHaveBeenCalledTimes(1);expect(c.saving()).toBe(true);pending.error({status:409});expect(c.saving()).toBe(false);expect(c.error()).toBeTruthy();expect(api.preferences).toHaveBeenCalledTimes(2)});
  it('shows load failures safely',()=>{const fixture=mount({preferences:()=>throwError(()=>new Error('private'))});expect(fixture.componentInstance.error()).toBe('The request could not be completed.');expect(fixture.nativeElement.textContent).not.toContain('private')});
  it('blocks inconsistent salary input before an API request',()=>{const api={preferences:()=>of(preferences()),updatePreferences:vi.fn()};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({minimumSalary:1000});c.form.markAsDirty();c.save();expect(api.updatePreferences).not.toHaveBeenCalled();expect(c.error()).toContain('Currency and period')});
  it('mirrors backend list, value, currency, and numeric salary limits',()=>{const api={preferences:()=>of(preferences()),updatePreferences:vi.fn()};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({targetRoles:Array.from({length:101},(_,i)=>`Role ${i}`).join('\n'),minimumSalary:1000.123,salaryCurrency:'US1',salaryPeriod:'MONTH'});c.form.markAsDirty();c.save();expect(c.form.controls.targetRoles.hasError('preferenceValues')).toBe(true);expect(c.form.controls.minimumSalary.hasError('numeric18Scale2')).toBe(true);expect(c.form.controls.salaryCurrency.hasError('pattern')).toBe(true);expect(api.updatePreferences).not.toHaveBeenCalled();c.form.patchValue({targetRoles:'x'.repeat(101),minimumSalary:10000000000000000,salaryCurrency:'USD'});expect(c.form.controls.targetRoles.hasError('preferenceValues')).toBe(true);expect(c.form.controls.minimumSalary.invalid).toBe(true)});
});
