import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { of, Subject, throwError } from 'rxjs';
import { vi } from 'vitest';
import { CandidateJobPreferences, CanonicalCv } from './job-hunting.models';
import { JobPreferencesPageComponent } from './job-preferences-page.component';
import { JobHuntingService } from './job-hunting.service';

const preferences=(overrides:Partial<CandidateJobPreferences>={}):CandidateJobPreferences=>({id:null,targetRoles:[],preferredTechnologies:[],acceptableLocations:[],workplaceTypes:[],employmentTypes:[],minimumSalary:null,salaryCurrency:null,salaryPeriod:null,version:0,createdAt:null,updatedAt:null,...overrides});
const missingCv=(overrides:Partial<CanonicalCv>={}):CanonicalCv=>({isConfigured:false,id:null,fileName:null,contentType:null,fileSizeBytes:null,contentHash:null,version:0,createdAt:null,updatedAt:null,...overrides});
const existingCv=(overrides:Partial<CanonicalCv>={}):CanonicalCv=>missingCv({isConfigured:true,id:'cv-1',fileName:'CV.pdf',contentType:'application/pdf',fileSizeBytes:2048,contentHash:'a'.repeat(64),version:1,createdAt:'2026-09-22T00:00:00Z',updatedAt:'2026-09-22T00:00:00Z',...overrides});
function mount(api:Record<string,unknown>):ComponentFixture<JobPreferencesPageComponent>{TestBed.configureTestingModule({imports:[JobPreferencesPageComponent],providers:[provideRouter([]),{provide:JobHuntingService,useValue:{canonicalCv:()=>of(missingCv()),...api}}]});const fixture=TestBed.createComponent(JobPreferencesPageComponent);fixture.detectChanges();return fixture}

describe('Job preferences page',()=>{
  afterEach(()=>TestBed.resetTestingModule());
  it('loads the initial no-row state without fabricating preferences',()=>{const fixture=mount({preferences:()=>of(preferences())});expect(fixture.componentInstance.loading()).toBe(false);expect(fixture.componentInstance.form.controls.targetRoles.value).toBe('');expect(fixture.componentInstance.form.pristine).toBe(true)});
  it('loads values and rebinds normalized server values and version after save',()=>{const api={preferences:()=>of(preferences({id:'p1',version:3,targetRoles:['Backend Developer']})),updatePreferences:vi.fn().mockReturnValueOnce(of(preferences({id:'p1',version:4,targetRoles:['Backend Developer','Full Stack Developer'],salaryCurrency:'USD',salaryPeriod:'MONTH',minimumSalary:1000}))).mockReturnValueOnce(of(preferences({id:'p1',version:5,targetRoles:['Backend Developer']})))};const fixture=mount(api);const c=fixture.componentInstance;expect(c.form.controls.targetRoles.value).toBe('Backend Developer');c.form.patchValue({targetRoles:' Full Stack Developer\nBackend Developer\nbackend developer ',minimumSalary:1000,salaryCurrency:'usd',salaryPeriod:'month'});c.form.markAsDirty();c.save();expect(api.updatePreferences).toHaveBeenNthCalledWith(1,expect.objectContaining({expectedVersion:3,targetRoles:['Full Stack Developer','Backend Developer','backend developer']}));expect(c.form.controls.targetRoles.value).toBe('Backend Developer\nFull Stack Developer');expect(c.form.controls.salaryCurrency.value).toBe('USD');expect(c.form.pristine).toBe(true);c.form.patchValue({targetRoles:'Backend Developer'});c.form.markAsDirty();c.save();expect(api.updatePreferences).toHaveBeenNthCalledWith(2,expect.objectContaining({expectedVersion:4}))});
  it('blocks duplicate saves and exposes safe conflict state',()=>{const pending=new Subject<CandidateJobPreferences>();const api={preferences:vi.fn(()=>of(preferences({version:1}))),updatePreferences:vi.fn(()=>pending)};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({targetRoles:'Backend'});c.form.markAsDirty();c.save();c.save();expect(api.updatePreferences).toHaveBeenCalledTimes(1);expect(c.saving()).toBe(true);pending.error({status:409});expect(c.saving()).toBe(false);expect(c.error()).toBeTruthy();expect(api.preferences).toHaveBeenCalledTimes(2)});
  it('shows load failures safely',()=>{const fixture=mount({preferences:()=>throwError(()=>new Error('sensitive-backend-detail'))});expect(fixture.componentInstance.error()).toBe('The request could not be completed.');expect(fixture.nativeElement.textContent).not.toContain('sensitive-backend-detail')});
  it('blocks inconsistent salary input before an API request',()=>{const api={preferences:()=>of(preferences()),updatePreferences:vi.fn()};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({minimumSalary:1000});c.form.markAsDirty();c.save();expect(api.updatePreferences).not.toHaveBeenCalled();expect(c.error()).toContain('Currency and period')});
  it('mirrors backend list, value, currency, and numeric salary limits',()=>{const api={preferences:()=>of(preferences()),updatePreferences:vi.fn()};const fixture=mount(api);const c=fixture.componentInstance;c.form.patchValue({targetRoles:Array.from({length:101},(_,i)=>`Role ${i}`).join('\n'),minimumSalary:1000.123,salaryCurrency:'US1',salaryPeriod:'MONTH'});c.form.markAsDirty();c.save();expect(c.form.controls.targetRoles.hasError('preferenceValues')).toBe(true);expect(c.form.controls.minimumSalary.hasError('numeric18Scale2')).toBe(true);expect(c.form.controls.salaryCurrency.hasError('pattern')).toBe(true);expect(api.updatePreferences).not.toHaveBeenCalled();c.form.patchValue({targetRoles:'x'.repeat(101),minimumSalary:10000000000000000,salaryCurrency:'USD'});expect(c.form.controls.targetRoles.hasError('preferenceValues')).toBe(true);expect(c.form.controls.minimumSalary.invalid).toBe(true)});
  it('renders one canonical CV workflow without picker or variant concepts',()=>{const fixture=mount({preferences:()=>of(preferences()),canonicalCv:()=>of(existingCv())});const text=fixture.nativeElement.textContent as string;expect(text).toContain('Canonical CV');expect(text).toContain('CV.pdf');expect(text).toContain('Preview / Download');expect(text).toContain('Replace CV');expect(text).toContain('PDF only · maximum 10 MiB');expect(text).not.toContain('Select CV');expect(text).not.toContain('Add another CV');expect(text).not.toContain('variant')});
  it('renders the missing state and validates PDF type and size before upload',()=>{const api={preferences:()=>of(preferences()),canonicalCv:()=>of(missingCv()),uploadCanonicalCv:vi.fn()};const fixture=mount(api);const c=fixture.componentInstance;expect(fixture.nativeElement.textContent).toContain('No canonical CV uploaded');expect(fixture.nativeElement.textContent).toContain('Upload CV');const input=fixture.nativeElement.querySelector('input[type="file"]') as HTMLInputElement;Object.defineProperty(input,'files',{value:[new File(['text'],'cv.txt',{type:'text/plain'})],configurable:true});input.dispatchEvent(new Event('change'));expect(c.cvError()).toContain('Only PDF');expect(api.uploadCanonicalCv).not.toHaveBeenCalled();Object.defineProperty(input,'files',{value:[new File([new Uint8Array(10*1024*1024+1)],'huge.pdf',{type:'application/pdf'})],configurable:true});input.dispatchEvent(new Event('change'));expect(c.cvError()).toContain('10 MiB')});
  it('prevents duplicate upload and refreshes metadata after success',()=>{const pending=new Subject<CanonicalCv>();const api={preferences:()=>of(preferences()),canonicalCv:vi.fn().mockReturnValueOnce(of(missingCv())).mockReturnValueOnce(of(existingCv())),uploadCanonicalCv:vi.fn(()=>pending)};const fixture=mount(api);const c=fixture.componentInstance;const file=new File(['%PDF-test'],'CV.pdf',{type:'application/pdf'});c.cvFile.set(file);c.uploadCv();c.uploadCv();fixture.detectChanges();expect(api.uploadCanonicalCv).toHaveBeenCalledTimes(1);expect(api.uploadCanonicalCv).toHaveBeenCalledWith(file,0);expect(c.cvUploading()).toBe(true);pending.next(existingCv());pending.complete();expect(c.cvUploading()).toBe(false);expect(c.cvFile()).toBeNull();expect(api.canonicalCv).toHaveBeenCalledTimes(2);expect(c.canonicalCv()?.version).toBe(1)});
  it('shows upload errors and refreshes safely after a stale-version conflict',()=>{const api={preferences:()=>of(preferences()),canonicalCv:vi.fn().mockReturnValueOnce(of(existingCv())).mockReturnValueOnce(of(existingCv({version:2}))),uploadCanonicalCv:vi.fn(()=>throwError(()=>({status:409})))};const fixture=mount(api);const c=fixture.componentInstance;c.cvFile.set(new File(['%PDF-new'],'CV.pdf',{type:'application/pdf'}));c.uploadCv();expect(c.cvUploading()).toBe(false);expect(c.cvError()).toBeTruthy();expect(api.canonicalCv).toHaveBeenCalledTimes(2);expect(c.canonicalCv()?.version).toBe(2)});
  it('previews through an authenticated blob and revokes its temporary URL',()=>{vi.useFakeTimers();const create=vi.spyOn(URL,'createObjectURL').mockReturnValue('blob:cv');const revoke=vi.spyOn(URL,'revokeObjectURL').mockImplementation(()=>{});const open=vi.spyOn(window,'open').mockReturnValue(null);const api={preferences:()=>of(preferences()),canonicalCv:()=>of(existingCv()),canonicalCvContent:vi.fn(()=>of(new Blob(['%PDF-test'],{type:'application/pdf'})))};const fixture=mount(api);fixture.componentInstance.previewCv();expect(api.canonicalCvContent).toHaveBeenCalledTimes(1);expect(create).toHaveBeenCalledTimes(1);expect(open).toHaveBeenCalledWith('blob:cv','_blank','noopener,noreferrer');vi.advanceTimersByTime(60_000);expect(revoke).toHaveBeenCalledWith('blob:cv');fixture.destroy();vi.useRealTimers()});
});
