export type JobSource='FACEBOOK'|'INSTAGRAM'|'TOPCV'|'VIETNAMWORKS'|'COMPANY_SITE'|'MANUAL'|'OTHER';
export type VerificationStatus='PENDING'|'VERIFIED'|'UNVERIFIED'|'LIKELY_EXPIRED';
export type SelectionStatus='PENDING_ANALYSIS'|'RECOMMENDED'|'APPROVED'|'SKIPPED';
export type ApplicationStatus='DRAFT'|'APPLIED'|'INTERVIEW'|'REJECTED'|'OFFER'|'WITHDRAWN';
export type ApplicationChannel='EMAIL'|'PLATFORM'|'MANUAL'|'OTHER';
export const applicationTransitions:Record<ApplicationStatus,ApplicationStatus[]>={DRAFT:['APPLIED','WITHDRAWN'],APPLIED:['INTERVIEW','REJECTED','WITHDRAWN'],INTERVIEW:['REJECTED','OFFER','WITHDRAWN'],OFFER:['WITHDRAWN'],REJECTED:[],WITHDRAWN:[]};
export interface JobSummary{id:string;companyName:string;positionTitle:string;location:string;source:string|null;sourceCount:number;verificationStatus:VerificationStatus;selectionStatus:SelectionStatus;archived:boolean;createdAt:string;updatedAt:string;applicationCount:number;version:number}
export interface RawSource{id:string;source:JobSource;sourceExternalId:string|null;sourceUrl:string|null;sourceUrlHash:string|null;rawContent:string;contentHash:string;companyTitleFingerprint:string|null;ingestionStatus:string;duplicateOfRawJobPostingId:string|null;metadata:unknown;discoveredAt:string;createdAt:string;updatedAt:string}
export interface ApplicationSummary{id:string;status:ApplicationStatus;channel:ApplicationChannel|null;appliedAt:string|null;lastActivityAt:string|null;version:number}
export interface JobDetail extends Omit<JobSummary,'source'|'sourceCount'|'archived'|'applicationCount'>{employmentType:string|null;workplaceType:string|null;salaryMinimum:number|null;salaryMaximum:number|null;salaryCurrency:string|null;salaryPeriod:string|null;experienceRequirements:string|null;description:string;technologyStack:string[];applicationEmail:string|null;applicationUrl:string|null;expiresAt:string|null;verifiedAt:string|null;archivedAt:string|null;notes:string|null;sources:RawSource[];applications:ApplicationSummary[]}
export interface JobWrite{companyName:string;positionTitle:string;location:string;employmentType:string|null;workplaceType:string|null;salaryMinimum:number|null;salaryMaximum:number|null;salaryCurrency:string|null;salaryPeriod:string|null;experienceRequirements:string|null;description:string;technologyStack:string[];applicationEmail:string|null;applicationUrl:string|null;expiresAt:string|null;notes:string|null}
export interface JobCreate extends JobWrite{source:JobSource;sourceExternalId:string|null;sourceUrl:string|null;rawContent:string}
export interface CandidateJobPreferences{id:string|null;targetRoles:string[];preferredTechnologies:string[];acceptableLocations:string[];workplaceTypes:string[];employmentTypes:string[];minimumSalary:number|null;salaryCurrency:string|null;salaryPeriod:string|null;version:number;createdAt:string|null;updatedAt:string|null}
export interface CandidateJobPreferencesWrite{expectedVersion:number;targetRoles:string[];preferredTechnologies:string[];acceptableLocations:string[];workplaceTypes:string[];employmentTypes:string[];minimumSalary:number|null;salaryCurrency:string|null;salaryPeriod:string|null}
export type JobFitStatus='MATCH'|'PARTIAL'|'MISMATCH'|'UNKNOWN';
export interface JobFitComponent{key:string;label:string;score:number|null;configuredWeight:number;status:JobFitStatus;explanation:string;evidence:string[]}
export interface JobFitAnalysis{jobPostingId:string;jobVersion:number;preferenceVersion:number;overallScore:number|null;availableWeight:number;totalConfiguredWeight:number;coveragePercent:number;jobVerificationStatus:string;components:JobFitComponent[];matchedTechnologies:string[];developingTechnologies:string[];missingTechnologies:string[];unknownFactors:string[]}
export interface ScreenshotSubmissionResult{rawJobPostingId:string;ingestionStatus:string;attachmentCount:number;created:boolean}
export interface RawJobPostingSummary{id:string;source:JobSource;ingestionStatus:string;discoveredAt:string;createdAt:string;attachmentCount:number;version:number}
export interface EventItem{id:string;eventType:string;fromStatus:string|null;toStatus:string|null;actorType:string;actorAdminUserId:string|null;note:string|null;metadata:unknown;occurredAt:string;createdAt:string}
export interface DocumentItem{id:string;documentType:string;versionLabel:string;fileName:string|null;storageKey:string|null;contentHash:string|null;metadata:unknown;createdAt:string;removedAt:string|null}
export interface ApplicationItem{id:string;jobPostingId:string;companyName:string;positionTitle:string;status:ApplicationStatus;channel:ApplicationChannel|null;appliedAt:string|null;lastActivityAt:string|null;version:number}
export interface ApplicationDetail{id:string;jobPostingId:string;status:ApplicationStatus;channel:ApplicationChannel|null;applicationEmail:string|null;applicationUrl:string|null;externalApplicationId:string|null;appliedAt:string|null;lastActivityAt:string|null;notes:string|null;version:number;createdAt:string;updatedAt:string;job:{id:string;companyName:string;positionTitle:string;location:string;verificationStatus:VerificationStatus;selectionStatus:SelectionStatus;archived:boolean};events:EventItem[];documents:DocumentItem[]}
